import assert from"node:assert/strict";import{chromium}from"playwright";import{createClient}from"@supabase/supabase-js";import{createServerClient}from"@supabase/ssr";
const{SUPABASE_URL:url,SUPABASE_ANON_KEY:anon,SUPABASE_SECRET_KEY:secret,APP_URL:app}=process.env;assert(url&&anon&&secret&&app);const root=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;const tournament="10000000-0000-4000-8000-000000000001";
async function auth(email){const api=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await api.auth.signInWithPassword({email,password:"development-only"});assert.ifError(error);let jar=[];const ssr=createServerClient(url,anon,{cookies:{getAll:()=>[],setAll:x=>{jar=x;}}});assert.ifError((await ssr.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token})).error);return{api,jar}}
const sessions={admin:await auth("player1@draftgg.test"),moderator:await auth("player2@draftgg.test"),support:await auth("player3@draftgg.test"),reporter:await auth("player5@draftgg.test"),subject:await auth("player6@draftgg.test"),organizer:await auth("player7@draftgg.test"),deactivate:await auth("player8@draftgg.test")};
const marker=`Phase08B-${Date.now()}`;const browser=await chromium.launch({headless:true});let assertions=0;async function pageFor(session,viewport={width:1440,height:900}){const context=await browser.newContext({viewport});await context.addCookies(session.jar.map(x=>({name:x.name,value:x.value,url:app})));return{context,page:await context.newPage()}}
// Player report through UI.
let{context,page}=await pageFor(sessions.reporter);await page.goto(app+"/reports");await page.getByLabel("Reported user ID (optional)").fill(uid(6));await page.getByLabel("Short reason").fill("Tournament misconduct");await page.getByLabel("What happened?").fill(`${marker} detailed misconduct report`);await page.getByRole("button",{name:"Submit report"}).click();await page.getByText("Report submitted privately").waitFor();assert((await page.locator("body").innerText()).includes("harassment"));assertions+=2;const{data:report}=await root.from("reports").select("id,reporter_user_id").ilike("description",`${marker}%`).single();assert(report);await context.close();
// Moderator creates case, note, and tournament restriction through UI.
({context,page}=await pageFor(sessions.moderator));await page.goto(app+"/platform-admin/reports");await page.getByLabel("Report ID").fill(report.id);await page.getByLabel("Subject user ID").fill(uid(6));await page.getByLabel("Tournament ID").fill(tournament);await page.getByLabel("Internal summary").fill(`${marker} internal case summary`);await page.getByRole("button",{name:"Create case"}).click();await page.getByText("Saved successfully.").waitFor();const{data:caseRow}=await root.from("moderation_cases").select("id,revision").eq("report_id",report.id).single();assert(caseRow);await page.goto(app+"/platform-admin/cases");await page.getByRole("heading",{name:"Add internal note"}).locator("..").getByLabel("Case ID").fill(caseRow.id);await page.getByLabel("Internal note").fill(`${marker} private moderator note`);await page.getByRole("button",{name:"Add note"}).click();await page.getByText("Saved successfully.").waitFor();const sanctionForm=page.getByRole("heading",{name:"Issue sanction"}).locator("..");await sanctionForm.getByLabel("Subject user ID").fill(uid(6));await sanctionForm.getByLabel("Case ID").fill(caseRow.id);await sanctionForm.getByLabel("Tournament ID").fill(tournament);await sanctionForm.getByLabel("Sanction scope").selectOption("tournament");await sanctionForm.getByLabel("Sanction type").selectOption("registration_restriction");await sanctionForm.getByLabel("Reason").fill(`${marker} tournament registration restricted`);await sanctionForm.getByRole("button",{name:"Issue sanction"}).click();await page.getByText("Saved successfully.").waitFor();const{data:sanction}=await root.from("sanctions").select("id,issued_by,case_id,tournament_id").eq("case_id",caseRow.id).single();assert.equal(sanction.tournament_id,tournament);assert.equal(sanction.issued_by,uid(2));assertions+=4;await context.close();
// Subject cannot see reporter/private note, sees sanction, appeals through UI.
({context,page}=await pageFor(sessions.subject));await page.goto(app+"/reports");let body=await page.locator("body").innerText();assert(!body.includes(report.id)&&!body.includes(uid(5)));await page.goto(app+"/moderation-status");body=await page.locator("body").innerText();assert(body.includes(`${marker} tournament registration restricted`));assert(!body.includes("private moderator note")&&!body.includes(uid(5)));await page.getByPlaceholder("Explain why this should be reviewed").fill(`${marker} request independent appeal review`);await page.getByRole("button",{name:"Appeal"}).click();await page.getByText("Appeal submitted.").waitFor();const{data:appeal}=await root.from("moderation_appeals").select("id").eq("sanction_id",sanction.id).single();assert(appeal);assertions+=4;await context.close();
// Eligible reviewer approves appeal; sanction disappears while history remains.
({context,page}=await pageFor(sessions.moderator));await page.goto(app+"/platform-admin/cases");const appealForm=page.getByRole("heading",{name:"Resolve appeal"}).locator("..");await appealForm.getByLabel("Appeal ID").fill(appeal.id);await appealForm.getByLabel("Appeal decision").selectOption("approve");await appealForm.getByLabel("Appeal resolution").fill(`${marker} appeal approved`);await appealForm.getByRole("button",{name:"Finalize appeal"}).click();await page.getByText("Saved successfully.").waitFor();assert.equal((await root.from("sanctions").select("active").eq("id",sanction.id).single()).data.active,false);assertions++;await context.close();
({context,page}=await pageFor(sessions.subject));await page.goto(app+"/moderation-status");assert((await page.locator("body").innerText()).includes("No active restrictions"));assertions++;await context.close();
// Complete requester/support/reopen workflow with internal-note privacy.
({context,page}=await pageFor(sessions.reporter));await page.goto(app+"/support");await page.getByLabel("Subject").fill(`${marker} support request`);await page.getByLabel("Message").fill(`${marker} initial support message`);await page.getByRole("button",{name:"Create ticket"}).click();await page.getByText("Support ticket created.").waitFor();const{data:ticket}=await root.from("support_tickets").select("id").eq("subject",`${marker} support request`).single();await page.goto(`${app}/support/${ticket.id}`);await page.getByLabel("Reply message").fill(`${marker} requester follow-up`);await page.getByRole("button",{name:"Reply"}).click();await page.getByText("Reply sent.").waitFor();await context.close();
({context,page}=await pageFor(sessions.support));await page.goto(app+"/platform-admin/support");const replyForm=page.getByRole("heading",{name:"Reply or internal note"}).locator("..");await replyForm.getByLabel("Ticket ID").fill(ticket.id);await replyForm.getByLabel("Support message").fill(`${marker} public agent reply`);await replyForm.getByRole("button",{name:"Post message"}).click();await page.getByText("Saved successfully.").waitFor();await page.waitForTimeout(300);await replyForm.getByLabel("Support message").fill(`${marker} INTERNAL SECRET NOTE`);await replyForm.locator('input[name="internal"]').check();await replyForm.getByRole("button",{name:"Post message"}).click();await page.waitForTimeout(300);const updateForm=page.getByRole("heading",{name:"Assign and update"}).locator("..");await updateForm.getByLabel("Ticket ID").fill(ticket.id);await updateForm.getByLabel("Assigned user ID").fill(uid(3));await updateForm.getByLabel("Ticket status").selectOption("resolved");await updateForm.getByRole("button",{name:"Update ticket"}).click();await page.waitForTimeout(500);assert.equal((await root.from("support_tickets").select("status").eq("id",ticket.id).single()).data.status,"resolved");await context.close();
({context,page}=await pageFor(sessions.reporter));await page.goto(`${app}/support/${ticket.id}?refresh=${encodeURIComponent(marker)}`,{waitUntil:"networkidle"});body=await page.locator("body").innerText();assert(body.includes(`${marker} public agent reply`));assert(!body.includes("INTERNAL SECRET NOTE"));await page.getByRole("button",{name:"Reopen ticket"}).click();await page.getByText("Ticket reopened.").waitFor();assert.equal((await root.from("support_tickets").select("status").eq("id",ticket.id).single()).data.status,"open");assertions+=4;await context.close();
// Organizer verification and restriction controls.
assert.ifError((await sessions.organizer.api.rpc("request_organizer_verification")).error);({context,page}=await pageFor(sessions.admin));await page.goto(app+"/platform-admin/organizers");await page.getByLabel("Organizer user ID").fill(uid(7));await page.getByLabel("Status").selectOption("verified");await page.getByLabel("Review notes").fill(`${marker} verified`);await page.getByRole("button",{name:"Review organizer"}).click();await page.getByText("Saved successfully.").waitFor();await page.goto(app+"/platform-admin/organizers");await page.getByLabel("Organizer user ID").fill(uid(7));await page.getByLabel("Status").selectOption("restricted");await page.getByLabel("Review notes").fill(`${marker} restricted`);await page.getByRole("button",{name:"Review organizer"}).click();await page.getByText("Saved successfully.").waitFor();assert.equal((await root.from("organizer_verifications").select("status").eq("user_id",uid(7)).single()).data.status,"restricted");assertions++;await context.close();
// Platform announcement creation and authoritative active-window display.
({context,page}=await pageFor(sessions.admin));await page.goto(app+"/platform-admin/announcements");await page.getByLabel("Title").fill(`${marker} announcement`);await page.getByLabel("Body").fill(`${marker} public operations notice`);await page.getByLabel("Starts").fill(new Date(Date.now()-60000).toISOString().slice(0,16));await page.getByText("Publish immediately").click();await page.getByRole("button",{name:"Create announcement"}).click();await page.getByText("Saved successfully.").waitFor();await page.goto(app);assert((await page.locator("body").innerText()).includes(`${marker} announcement`));assertions++;await context.close();
// Audit server filters and explicit pagination preserve query state.
await root.from("audit_events").insert(Array.from({length:24},(_,i)=>({actor_user_id:uid(1),event_type:`${marker}_AUDIT`,entity_type:"phase08b",payload:{safe:i}})));({context,page}=await pageFor(sessions.admin));await page.goto(app+"/platform-admin/audit");await page.getByLabel("Actor ID").fill(uid(1));await page.getByLabel("Event type").fill(`${marker}_AUDIT`);await page.getByLabel("Entity type").fill("phase08b");await page.getByLabel("Page size").selectOption("10");await Promise.all([page.waitForURL(url=>url.searchParams.get("event")===`${marker}_AUDIT`),page.getByRole("button",{name:"Apply filters"}).click()]);assert((await page.locator("body").innerText()).includes("24 results"));await Promise.all([page.waitForURL(url=>url.searchParams.get("page")==="2"),page.getByRole("link",{name:"Next"}).click()]);assert.equal(await page.getByLabel("Event type").inputValue(),`${marker}_AUDIT`);await Promise.all([page.waitForURL(url=>url.searchParams.get("page")==="1"),page.getByRole("link",{name:"Previous"}).click()]);assertions+=4;await context.close();
// Confirmed account deactivation UI preserves profile/history identity.
({context,page}=await pageFor(sessions.deactivate));await page.goto(app+"/settings");await page.getByLabel("Reason").fill(`${marker} deactivation test`);await page.getByLabel("Type DEACTIVATE to confirm").fill("DEACTIVATE");await page.getByRole("button",{name:"Deactivate account"}).click();await page.getByText("Account deactivated.").waitFor();assert((await root.from("account_operational_status").select("deactivated_at").eq("user_id",uid(8)).single()).data.deactivated_at);assert((await root.from("profiles").select("id").eq("id",uid(8)).single()).data);assertions+=2;await context.close();
// Role matrix and mobile overflow for closure routes.
for(const [session,route,allowed]of[[sessions.support,"/platform-admin/cases",false],[sessions.moderator,"/platform-admin/config",false],[sessions.reporter,"/platform-admin",false],[sessions.admin,"/platform-admin/config",true]]){({context,page}=await pageFor(session,{width:390,height:844}));await page.goto(app+route);assert.equal(page.url()===app+route,allowed);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);assertions+=2;await context.close()}
await browser.close();console.log(JSON.stringify({result:"PASS",assertions,reportLifecycle:"PASS",supportLifecycle:"PASS",organizerControls:"PASS",announcementPublishing:"PASS",auditFiltersPagination:"PASS",accountDeactivation:"PASS",privacy:"PASS",mobile:"PASS"}));
