begin;create extension if not exists pgtap with schema extensions;select plan(30);
select has_table('public','player_game_accounts','normalized accounts exist');select has_table('public','dota_profile_snapshots','profile snapshots exist');select has_table('public','external_sync_jobs','sync jobs exist');select has_table('public','external_provider_cache','private cache exists');select has_table('public','external_provider_health','health exists');select has_table('public','dota_matches','matches exist');select has_table('public','dota_match_players','match players exist');select has_table('public','match_external_links','canonical links exist');
select has_function('public','link_dota_account',array['text'],'account link RPC exists');select has_function('public','queue_external_sync',array['uuid','text'],'queue RPC exists');select has_function('public','link_external_dota_match',array['uuid','bigint'],'match link RPC exists');
select has_function('public','reconcile_external_dota_match',array['uuid'],'participant reconciliation RPC exists');
set local role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000005',true);
select lives_ok($$select public.link_dota_account('123456789')$$,'account ID links');
select is((select steam_id64::text from public.player_game_accounts where player_id=auth.uid()),'76561198083722517','conversion exact');
select throws_ok($$select public.link_dota_account('https://evil.test/76561198083722517')$$,'P0001','INVALID_DOTA_ACCOUNT','arbitrary URL rejected');
select throws_ok($$select public.link_dota_account('4294967296')$$,'P0001','INVALID_DOTA_ACCOUNT','uint32 overflow rejected');
select lives_ok($$select public.queue_external_sync((select id from public.player_game_accounts where player_id=auth.uid()),'profile_sync')$$,'owner queues sync');
select lives_ok($$select public.queue_external_sync((select id from public.player_game_accounts where player_id=auth.uid()),'profile_sync')$$,'duplicate request idempotent');
select is((select count(*) from public.external_sync_jobs where created_by=auth.uid()),1::bigint,'one active job');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000006',true);
select is((select count(*) from public.player_game_accounts),0::bigint,'other user cannot read identity');
select throws_ok($$select public.queue_external_sync((select id from public.player_game_accounts limit 1),'profile_sync')$$,'P0001','UNAUTHORIZED','other user cannot queue owner job');
reset role;insert into public.dota_heroes(hero_id,internal_name,localized_name)values(1,'npc_dota_hero_antimage','Anti-Mage');insert into public.dota_matches(match_id,radiant_win,parse_state,source_hash)values(8123456789,true,'parsed',md5('a')||md5('b'));
insert into public.dota_match_players(match_id,slot,account_id,hero_id,is_radiant,kills,deaths,assists)values(8123456789,0,123456789,1,true,10,2,15),(8123456789,128,987654321,1,false,null,null,null);
set local role anon;select is((select count(*) from public.dota_matches),0::bigint,'unlinked external match private');select throws_ok($$select count(*) from public.dota_profile_snapshots$$,'42501','permission denied for table dota_profile_snapshots','anonymous snapshot access denied');
set local role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000005',true);
select throws_ok($$select public.link_external_dota_match('00000000-0000-0000-0000-000000000000',8123456789)$$,'P0001','UNAUTHORIZED_REFEREE','unrelated participant cannot link');
reset role;
select ok((select relrowsecurity from pg_class where oid='public.external_provider_cache'::regclass),'cache has RLS');
select ok(not has_table_privilege('anon','public.external_provider_cache','select'),'anon has no cache grant');
select ok(not has_table_privilege('authenticated','public.external_provider_cache','select'),'authenticated has no cache grant');
select ok(not has_function_privilege('anon','public.link_dota_account(text)','execute'),'anon cannot link');
select is((select count(*) from public.external_provider_health),2::bigint,'both providers initialized');
select ok((select definition ilike '%completed%' from pg_views where schemaname='public'and viewname='public_dota_match_stats'),'public stats are canonical-status gated');
select * from finish();rollback;
