begin;create extension if not exists pgtap;select plan(17);
select has_table('private','rate_limit_buckets','durable buckets exist outside exposed schema');
select has_table('public','rate_limit_events','safe aggregate telemetry exists');
select has_function('public','consume_rate_limit',array['text','text','integer','integer'],'atomic limiter exists');
select function_privs_are('public','consume_rate_limit',array['text','text','integer','integer'],'service_role',array['EXECUTE'],'service role alone executes limiter');
select function_privs_are('public','consume_rate_limit',array['text','text','integer','integer'],'authenticated',array[]::text[],'authenticated cannot forge limiter identity');
select function_privs_are('public','consume_rate_limit',array['text','text','integer','integer'],'anon',array[]::text[],'anonymous callers cannot forge limiter identity');
select is((select allowed from public.consume_rate_limit('report',repeat('a',64),2,3600)),true,'under limit accepted');
select is((select allowed from public.consume_rate_limit('report',repeat('a',64),2,3600)),true,'threshold accepted');
select is((select allowed from public.consume_rate_limit('report',repeat('a',64),2,3600)),false,'next request rejected');
select is((select allowed from public.consume_rate_limit('report',repeat('b',64),2,3600)),true,'independent identities do not interfere');
select is((select allowed from public.consume_rate_limit('support_ticket',repeat('a',64),2,3600)),true,'route scopes are independent');
select throws_ok($$select * from public.consume_rate_limit('forged_scope',repeat('a',64),2,3600)$$,'P0001','INVALID_RATE_LIMIT_POLICY','scope allowlist rejects forged policy');
select is((select count(*) from public.rate_limit_events where scope='report'),4::bigint,'aggregate allow and rejection telemetry recorded');
insert into private.rate_limit_buckets(scope,key_hash,window_start,window_seconds,request_count)values('report',repeat('d',64),now()-interval'2 hours',3600,99);
select is((select allowed from public.consume_rate_limit('report',repeat('d',64),2,3600)),true,'expired windows reset without carrying old usage');
select is((select allowed from public.consume_rate_limit('report',repeat('e',64),1,3600)),true,'anonymous-derived identity is accepted under limit');
select is((select allowed from public.consume_rate_limit('report',repeat('f',64),1,3600)),true,'authenticated-derived identity is independent');
select is((select allowed from public.consume_rate_limit('report',repeat('f',64),1,3600)),false,'same authenticated identity shares state across sessions and instances');
select *from finish();rollback;
