begin;create extension if not exists pgtap with schema extensions;select plan(35);
select has_type('public','competition_format','competition format enum exists');
select has_type('public','match_status','match status enum exists');
select has_table('public','competition_settings','competition settings exist');
select has_table('public','competition_stages','competition stages exist');
select has_table('public','competition_groups','competition groups exist');
select has_table('public','matches','canonical matches exist');
select has_table('public','match_games','game detail exists');
select has_table('public','match_check_ins','normalized check-in exists');
select has_table('public','match_lineups','lineup snapshots exist');
select has_table('public','match_result_submissions','append-only result reports exist');
select has_table('public','match_disputes','disputes exist');
select has_table('public','competition_result_snapshots','final snapshots exist');
select has_view('public','public_matches','safe public match projection exists');
select has_view('public','public_standings','derived standings exist');
select has_function('public','generate_competition_schedule',array['uuid','timestamp with time zone','integer'],'schedule RPC exists');
select has_function('public','submit_match_result',array['uuid','integer','integer','text','text','uuid'],'result RPC exists');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',true);set local role authenticated;
select lives_ok($$select public.configure_competition('10000000-0000-4000-8000-000000000001','round_robin',3,5,3,1,0,'["points","head_to_head","game_difference","games_won"]')$$,'organizer configures competition');
select is(public.generate_competition_schedule('10000000-0000-4000-8000-000000000001',clock_timestamp()+interval '1 hour',60),15,'six-team round robin creates 15 matches');
reset role;
select is((select count(*)from public.matches where tournament_id='10000000-0000-4000-8000-000000000001'),15::bigint,'schedule contains every pair once');
select is((select count(*)from(select least(team_a_id,team_b_id),greatest(team_a_id,team_b_id),count(*)from public.matches group by 1,2 having count(*)>1)x),0::bigint,'schedule has no duplicate matchup');
select is((select count(*)from public.matches where team_a_id=team_b_id),0::bigint,'team never plays itself');
select throws_ok($$set local role authenticated;select public.generate_competition_schedule('10000000-0000-4000-8000-000000000001',now(),60)$$,'P0001',null,'regeneration cannot overwrite schedule');reset role;
update public.matches set status='live' where id=(select id from public.matches order by match_number limit 1);
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',true);set local role authenticated;
select lives_ok($$select public.submit_match_result((select id from public.matches order by match_number limit 1),2,0,null,null,'60000000-0000-4000-8000-000000000001')$$,'participating captain submits result');
select is((public.submit_match_result((select id from public.matches order by match_number limit 1),2,0,null,null,'60000000-0000-4000-8000-000000000001')->>'code'),'DUPLICATE_REQUEST','duplicate request is idempotent');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',true);set local role authenticated;
select lives_ok($$select public.respond_to_match_result((select id from public.match_result_submissions limit 1),true,null,'60000000-0000-4000-8000-000000000002')$$,'opponent confirms matching result');
reset role;
select is((select status::text from public.matches order by match_number limit 1),'completed','confirmation completes match once');
select is((select wins from public.public_standings where team_id='40000000-0000-4000-8000-000000000001'),1::bigint,'standings derive winner');
select is((select points from public.public_standings where team_id='40000000-0000-4000-8000-000000000001'),3::bigint,'configured win points apply');
select is((select game_difference from public.public_standings where team_id='40000000-0000-4000-8000-000000000001'),2::bigint,'game difference is canonical');
set local role anon;select lives_ok($$select * from public.public_matches$$,'anonymous reads safe match projection');
select ok(not exists(select 1 from information_schema.columns where table_schema='public'and table_name='public_matches'and column_name in('lobby_password','forfeit_reason')),'public projection omits lobby password and forfeit reason');
reset role;set local role authenticated;select lives_ok($$update public.matches set winner_team_id='40000000-0000-4000-8000-000000000002' where id=(select id from public.matches limit 1)$$,'unauthorized direct winner update is safely filtered');reset role;
select is((select winner_team_id from public.matches order by match_number limit 1),'40000000-0000-4000-8000-000000000001'::uuid,'filtered direct mutation cannot alter canonical winner');
select ok(exists(select 1 from public.audit_events where event_type='SCHEDULE_GENERATED'),'schedule generation audited');
select ok(exists(select 1 from public.audit_events where event_type='MATCH_COMPLETED'),'completion audited');
select * from finish();rollback;
