import assert from "node:assert/strict";
import { chromium } from "playwright";
import { createClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";
const { SUPABASE_URL: url, SUPABASE_ANON_KEY: key, APP_URL: app } = process.env; assert(url && key && app);
async function cookieFor(email) { const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); const {data,error}=await auth.auth.signInWithPassword({email,password:"development-only"}); assert.ifError(error); let jar=[]; const ssr=createServerClient(url,key,{cookies:{getAll:()=>[],setAll:x=>{jar=x;}}}); assert.ifError((await ssr.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token})).error); return jar; }
const cookies = { admin: await cookieFor("player1@draftgg.test"), moderator: await cookieFor("player2@draftgg.test"), support: await cookieFor("player3@draftgg.test"), user: await cookieFor("player5@draftgg.test") };
const browser=await chromium.launch({headless:true}); let assertions=0;
for(const viewport of [{width:1440,height:900},{width:390,height:844}]) {
  const makeContext=async jar=>{const context=await browser.newContext({viewport});await context.addCookies(jar.map(x=>({name:x.name,value:x.value,url:app})));return context;};
  const adminContext=await makeContext(cookies.admin),adminPage=await adminContext.newPage(); for(const route of ["/platform-admin","/platform-admin/users","/platform-admin/organizers","/platform-admin/reports","/platform-admin/cases","/platform-admin/sanctions","/platform-admin/support","/platform-admin/announcements","/platform-admin/audit","/platform-admin/health","/platform-admin/config"]) { const r=await adminPage.goto(app+route); assert.equal(r?.status(),200,route); assert.equal(adminPage.url(),app+route,`${route} redirected`); assertions+=2; assert.equal(await adminPage.locator("h1").count(),1); assertions++; assert.equal(await adminPage.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,`${route} overflow`); assertions++; } await adminContext.close();
  const moderatorContext=await makeContext(cookies.moderator),moderatorPage=await moderatorContext.newPage(); await moderatorPage.goto(app+"/platform-admin/config"); assert.equal(moderatorPage.url(),app+"/dashboard"); assertions++; await moderatorContext.close();
  const supportContext=await makeContext(cookies.support),supportPage=await supportContext.newPage(); await supportPage.goto(app+"/platform-admin/cases"); assert.equal(supportPage.url(),app+"/dashboard"); assertions++; assert.equal((await supportPage.goto(app+"/platform-admin/support"))?.status(),200); assert.equal(supportPage.url(),app+"/platform-admin/support"); assertions+=2; await supportContext.close();
  const userContext=await makeContext(cookies.user),userPage=await userContext.newPage(); for(const route of ["/reports","/support","/moderation-status"]) { const r=await userPage.goto(app+route); assert.equal(r?.status(),200); assert.equal(userPage.url(),app+route); assertions+=2; const body=await userPage.locator("body").innerText(); assert(!/internal support note|moderation_case_notes|evidence_path|reporter_user_id/i.test(body)); assertions++; assert.equal(await userPage.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false); assertions++; } await userContext.close();
}
await browser.close(); console.log(JSON.stringify({result:"PASS",assertions,viewports:2}));
