begin;create extension if not exists pgtap with schema extensions;select plan(20);
insert into public.moderation_cases(id,subject_user_id,case_type,summary)values('99000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000005','phase08b','Phase08B note fixture');
select has_function('public','reply_support_ticket',array['uuid','text','boolean'],'support reply RPC exists');
select has_function('public','reopen_support_ticket',array['uuid'],'support reopen RPC exists');
select has_function('public','add_moderation_case_note',array['uuid','text'],'case note RPC exists');
select has_function('public','create_platform_announcement',array['text','text','announcement_severity','text','timestamp with time zone','timestamp with time zone','boolean','text'],'announcement RPC exists');
set local role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000005',true);
select lives_ok($$select public.create_support_ticket('technical','Phase08B ticket','Initial browser-safe support message')$$,'user creates support ticket');
select lives_ok($$select public.reply_support_ticket((select id from public.support_tickets where user_id=auth.uid()order by created_at desc limit 1),'Requester follow-up',false)$$,'requester replies');
select throws_ok($$select public.reply_support_ticket((select id from public.support_tickets where user_id=auth.uid()order by created_at desc limit 1),'forged internal',true)$$,'42501','INTERNAL_NOTE_FORBIDDEN','requester cannot add internal note');
select lives_ok($$select public.close_support_ticket((select id from public.support_tickets where user_id=auth.uid()order by created_at desc limit 1))$$,'requester closes ticket');
select lives_ok($$select public.reopen_support_ticket((select id from public.support_tickets where user_id=auth.uid()order by created_at desc limit 1))$$,'requester reopens ticket');
select is((select status::text from public.support_tickets where user_id=auth.uid()order by created_at desc limit 1),'open','reopened ticket is open');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',true);
select lives_ok($$select public.reply_support_ticket((select id from public.support_tickets order by created_at desc limit 1),'private staff context',true)$$,'support adds internal note');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000005',true);
select is((select count(*)::integer from public.support_ticket_messages where message='private staff context'),0,'internal note remains hidden from requester');
select throws_ok($$select public.confirm_account_deactivation('wrong','reason')$$,'P0001','EXPLICIT_CONFIRMATION_REQUIRED','deactivation requires confirmation');
select lives_ok($$select public.confirm_account_deactivation('DEACTIVATE','Phase08B validation')$$,'confirmed deactivation works');
select ok((select deactivated_at is not null from public.account_operational_status where user_id=auth.uid()),'account status is deactivated');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.create_platform_announcement('Phase08B notice','Browser-visible operations notice','notice','all',now()-interval'1 minute',now()+interval'1 hour',true,null)$$,'admin publishes announcement');
select ok(exists(select 1 from public.public_active_announcements where title='Phase08B notice'),'active announcement reaches safe public view');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.create_platform_announcement('Critical','Denied','critical','all',now(),null,true,null)$$,'42501','EXPLICIT_SUPER_ADMIN_CONFIRMATION_REQUIRED','moderator cannot publish critical announcement');
select lives_ok($$select public.add_moderation_case_note((select id from public.moderation_cases limit 1),'Append-only browser workflow note')$$,'moderator adds append-only case note');
select ok((select count(*)>=5 from public.audit_events where event_type in('SUPPORT_REPLY_ADDED','SUPPORT_TICKET_CLOSED','SUPPORT_TICKET_REOPENED','ACCOUNT_DEACTIVATED','PLATFORM_ANNOUNCEMENT_CREATED','MODERATION_CASE_NOTE_ADDED')),'Phase08B sensitive actions are audited');
select * from finish();rollback;
