import{accountIdFromSteamId64,steamId64FromAccountId}from"../ids";import{providerJson}from"./request";import type{DotaHero,DotaMatch,DotaProfile,DotaProvider,RequestPolicy}from"./types";
const BASE="https://api.opendota.com/api";
type RawPlayer={profile?:{account_id?:number;personaname?:string|null;avatarfull?:string|null;profileurl?:string|null};rank_tier?:number|null;leaderboard_rank?:number|null};
type RawMatch={match_id:number;radiant_win?:boolean;start_time?:number;duration?:number;game_mode?:number;lobby_type?:number;patch?:number;replay_url?:string;version?:number;players?:Array<{player_slot:number;account_id?:number;hero_id?:number;kills?:number;deaths?:number;assists?:number;gold_per_min?:number;xp_per_min?:number}>};
export class OpenDotaProvider implements DotaProvider{readonly name="opendota" as const;constructor(private key?:string,private policy:RequestPolicy={}){}
 private url(path:string){const url=new URL(BASE+path);if(this.key)url.searchParams.set("api_key",this.key);return url;}
 async getPlayerProfile(accountId:string,signal?:AbortSignal):Promise<DotaProfile>{const raw=await providerJson<RawPlayer>(this.url(`/players/${accountId}`),{signal},this.policy,"player");return{provider:this.name,accountId,steamId64:steamId64FromAccountId(accountId),personaName:raw.profile?.personaname??null,avatarUrl:raw.profile?.avatarfull??null,profileVisibility:raw.profile?"public":"private",rankTier:raw.rank_tier??null,leaderboardRank:raw.leaderboard_rank??null};}
 async getPlayerRecentMatches(accountId:string,signal?:AbortSignal){const rows=await providerJson<RawMatch[]>(this.url(`/players/${accountId}/recentMatches`),{signal},this.policy,"player");return rows.map(row=>this.mapMatch(row));}
 async getMatch(matchId:string,signal?:AbortSignal){const raw=await providerJson<RawMatch>(this.url(`/matches/${matchId}`),{signal},this.policy);return this.mapMatch(raw);}
 async getHeroes(signal?:AbortSignal):Promise<DotaHero[]>{const rows=await providerJson<Array<{id:number;name:string;localized_name:string;primary_attr?:string}>>(this.url("/heroes"),{signal},this.policy);return rows.map(h=>({heroId:h.id,internalName:h.name,localizedName:h.localized_name,primaryAttribute:h.primary_attr??null}));}
 async healthCheck(signal?:AbortSignal){try{await providerJson(this.url("/health"),{signal},{...this.policy,maxRetries:0});return true;}catch{return false;}}
 private mapMatch(raw:RawMatch):DotaMatch{return{provider:this.name,matchId:String(raw.match_id),radiantWin:raw.radiant_win??null,startTime:raw.start_time?new Date(raw.start_time*1000).toISOString():null,durationSeconds:raw.duration??null,gameMode:raw.game_mode??null,lobbyType:raw.lobby_type??null,patch:raw.patch??null,parseState:raw.version?"parsed":"unparsed",replayUrl:raw.replay_url??null,players:(raw.players??[]).map(p=>({slot:p.player_slot,accountId:p.account_id==null?null:String(p.account_id),heroId:p.hero_id??null,isRadiant:p.player_slot<128,kills:p.kills??null,deaths:p.deaths??null,assists:p.assists??null,gpm:p.gold_per_min??null,xpm:p.xp_per_min??null}))};}}
export{accountIdFromSteamId64};
