import { notFound } from "next/navigation";
import Link from "next/link";
import { requirePlatformRole, type PlatformRole } from "@/lib/platform/auth";
import { OperationsControls } from "@/components/platform/operations-controls";

const access: Record<string, PlatformRole[]> = {
  users: ["super_admin"], organizers: ["super_admin", "platform_moderator"], reports: ["super_admin", "platform_moderator"], cases: ["super_admin", "platform_moderator"], sanctions: ["super_admin", "platform_moderator"], support: ["super_admin", "support_agent"], announcements: ["super_admin", "platform_moderator"], audit: ["super_admin", "platform_moderator"], health: ["super_admin", "platform_moderator"], integrations:["super_admin","platform_moderator"], config: ["super_admin"],
};

const safe = (value: unknown) => typeof value === "string" ? value : value == null ? "—" : JSON.stringify(value);

type Query = Record<string,string|string[]|undefined>;
const one=(x:string|string[]|undefined)=>Array.isArray(x)?x[0]:x;
export default async function OperationsSection({ params,searchParams }: { params: Promise<{ section: string }>;searchParams:Promise<Query> }) {
  const { section } = await params;
  const query=await searchParams;
  if (!access[section]) notFound();
  const { supabase } = await requirePlatformRole(access[section]);
  let rows: Record<string, unknown>[] = [];
  let columns: string[] = [];
  if (section === "users") { const { data } = await supabase.from("platform_admins").select("user_id,role,status,granted_at,revoked_at").order("granted_at", { ascending: false }).limit(50); rows = data ?? []; columns = ["user_id","role","status","granted_at"]; }
  if (section === "organizers") { const { data } = await supabase.from("organizer_verifications").select("user_id,status,requested_at,reviewed_at").order("updated_at", { ascending: false }).limit(50); rows = data ?? []; columns = ["user_id","status","requested_at","reviewed_at"]; }
  if (section === "reports") { const { data } = await supabase.from("reports").select("id,report_type,status,priority,tournament_id,created_at").order("created_at", { ascending: false }).limit(25); rows = data ?? []; columns = ["id","report_type","status","priority","created_at"]; }
  if (section === "cases") { const { data } = await supabase.from("moderation_cases").select("id,case_type,status,severity,assigned_to,created_at").order("created_at", { ascending: false }).limit(25); rows = data ?? []; columns = ["id","case_type","status","severity","assigned_to","created_at"]; }
  if (section === "sanctions") { const { data } = await supabase.from("sanctions").select("id,user_id,scope,sanction_type,active,starts_at,expires_at").order("created_at", { ascending: false }).limit(50); rows = data ?? []; columns = ["user_id","scope","sanction_type","active","expires_at"]; }
  if (section === "support") { const { data } = await supabase.from("support_tickets").select("id,category,subject,status,priority,assigned_to,updated_at").order("updated_at", { ascending: false }).limit(25); rows = data ?? []; columns = ["id","category","subject","status","priority","updated_at"]; }
  if (section === "announcements") { const { data } = await supabase.from("platform_announcements").select("id,title,severity,target,published,starts_at,ends_at").order("created_at", { ascending: false }).limit(50); rows = data ?? []; columns = ["title","severity","target","published","starts_at","ends_at"]; }
  let auditCount:number|null=null;const page=Math.max(1,Number(one(query.page))||1),pageSize=Math.min(50,Math.max(10,Number(one(query.pageSize))||15));
  if (section === "audit") { const actor=one(query.actor),event=one(query.event),tournament=one(query.tournament),entityType=one(query.entityType),entityId=one(query.entityId),from=one(query.from),to=one(query.to),hasFilters=Boolean(actor||event||tournament||entityType||entityId||from||to);let builder=supabase.from("audit_events").select("id,actor_user_id,event_type,tournament_id,entity_type,entity_id,created_at",{count:hasFilters?"exact":"planned"});if(actor)builder=builder.eq("actor_user_id",actor);if(event)builder=builder.eq("event_type",event);if(tournament)builder=builder.eq("tournament_id",tournament);if(entityType)builder=builder.eq("entity_type",entityType);if(entityId)builder=builder.eq("entity_id",entityId);if(from)builder=builder.gte("created_at",from);if(to)builder=builder.lte("created_at",`${to}T23:59:59.999Z`);const {data,count}=await builder.order("created_at",{ascending:false}).range((page-1)*pageSize,page*pageSize-1);rows=data??[];auditCount=count;columns=["actor_user_id","event_type","tournament_id","entity_type","entity_id","created_at"]; }
  if (section === "health") { const [health, jobs] = await Promise.all([supabase.from("platform_health").select("*"), supabase.from("job_health").select("job_name,status,last_success_at,last_failure_at,last_duration_ms")]); rows = [...(health.data ?? []), ...(jobs.data ?? [])]; columns = Array.from(new Set(rows.flatMap(Object.keys))); }
  if(section==="integrations"){const[health,jobs]=await Promise.all([supabase.from("provider_operational_metrics").select("*"),supabase.from("external_sync_jobs").select("provider,job_type,status,attempts,run_after,last_error_code,created_at").order("created_at",{ascending:false}).limit(25)]);rows=[...(health.data??[]),...(jobs.data??[])];columns=["provider","status","circuit_state","job_type","attempts","requests_minute","requests_hour","requests_day","cache_hits_day","recent_error_count","rate_limit_count","queue_depth","next_retry_at","last_success_at","last_failure_at","last_error_code"];}
  if (section === "config") { const { data } = await supabase.from("platform_config").select("key,value,description,updated_at").order("key"); rows = data ?? []; columns = ["key","value","description","updated_at"]; }
  const preserved=new URLSearchParams();for(const[key,value]of Object.entries(query)){if(key!=="page"&&typeof value==="string"&&value)preserved.set(key,value)}
  const hrefFor=(target:number)=>{const p=new URLSearchParams(preserved);p.set("page",String(target));return`/platform-admin/audit?${p}`};
  return <><h1 className="text-3xl font-bold capitalize">{section}</h1><p className="muted mt-2">Authorized operational view. Results are capped and ordered by urgency or recency.</p><OperationsControls section={section}/>{section==="audit"&&<form method="get" className="card mt-6 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><InputFilter name="actor" label="Actor ID" value={one(query.actor)}/><InputFilter name="event" label="Event type" value={one(query.event)}/><InputFilter name="tournament" label="Tournament ID" value={one(query.tournament)}/><InputFilter name="entityType" label="Entity type" value={one(query.entityType)}/><InputFilter name="entityId" label="Entity ID" value={one(query.entityId)}/><InputFilter name="from" label="Date from" type="date" value={one(query.from)}/><InputFilter name="to" label="Date to" type="date" value={one(query.to)}/><label className="text-sm">Page size<select name="pageSize" defaultValue={pageSize} className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line)] bg-[#081016] px-3"><option>10</option><option>15</option><option>25</option><option>50</option></select></label><button className="rounded-lg bg-[var(--accent)] px-4 py-2 font-semibold text-[#06110f]">Apply filters</button></form>}<div className="card mt-6 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-[var(--line)] text-xs uppercase text-[var(--muted)]"><tr>{columns.map((column) => <th scope="col" className="px-4 py-3" key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-b border-[var(--line)] last:border-0" key={String(row.id ?? row.user_id ?? row.key ?? index)}>{columns.map((column) => <td className="max-w-72 truncate px-4 py-3" key={column}>{safe(row[column])}</td>)}</tr>)}{rows.length === 0 && <tr><td className="muted px-4 py-8 text-center" colSpan={Math.max(columns.length,1)}>No items in this queue.</td></tr>}</tbody></table></div>{section==="audit"&&<nav aria-label="Audit pagination" className="mt-4 flex items-center justify-between"><Link aria-disabled={page===1} className={`rounded border border-[var(--line)] px-4 py-2 ${page===1?"pointer-events-none opacity-40":""}`} href={hrefFor(page-1)}>Previous</Link><span className="muted text-sm">Page {page} · {auditCount??0} results</span><Link aria-disabled={page*pageSize>=(auditCount??0)} className={`rounded border border-[var(--line)] px-4 py-2 ${page*pageSize>=(auditCount??0)?"pointer-events-none opacity-40":""}`} href={hrefFor(page+1)}>Next</Link></nav>}</>;
}

function InputFilter({name,label,value,type="text"}:{name:string;label:string;value?:string;type?:string}){return <label className="text-sm">{label}<input className="mt-1 min-h-10 w-full rounded-lg border border-[var(--line)] bg-[#081016] px-3" name={name} type={type} defaultValue={value}/></label>}
