create function public.add_moderation_case_note(p_case uuid,p_note text)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;if length(trim(p_note))<3 then raise exception'NOTE_TOO_SHORT'using errcode='P0001';end if;insert into public.moderation_case_notes(case_id,author_user_id,note)values(p_case,(select auth.uid()),p_note)returning id into v_id;perform private.audit_platform('MODERATION_CASE_NOTE_ADDED','moderation_case',p_case);return v_id;end$$;

create function public.update_support_ticket(p_id uuid,p_status public.support_status,p_priority public.case_severity default null,p_assigned_to uuid default null)returns void language plpgsql security definer set search_path=''as $$declare v_old public.support_status;begin if not public.is_support_agent()then raise exception'SUPPORT_AGENT_REQUIRED'using errcode='42501';end if;select status into v_old from public.support_tickets where id=p_id for update;if not found then raise exception'TICKET_NOT_FOUND'using errcode='P0001';end if;if v_old='closed'and p_status not in('closed','open')then raise exception'INVALID_SUPPORT_TRANSITION'using errcode='P0001';end if;update public.support_tickets set status=p_status,priority=coalesce(p_priority,priority),assigned_to=coalesce(p_assigned_to,assigned_to),closed_at=case when p_status='closed'then now()else null end,updated_at=now()where id=p_id;perform private.audit_platform('SUPPORT_TICKET_UPDATED','support_ticket',p_id,jsonb_build_object('from',v_old,'to',p_status));end$$;

create function public.reply_support_ticket(p_id uuid,p_message text,p_internal boolean default false)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;v_owner uuid;v_staff boolean:=public.is_support_agent();begin select user_id into v_owner from public.support_tickets where id=p_id;if v_owner is null or(not v_staff and v_owner<>(select auth.uid()))then raise exception'TICKET_NOT_FOUND'using errcode='42501';end if;if p_internal and not v_staff then raise exception'INTERNAL_NOTE_FORBIDDEN'using errcode='42501';end if;if length(trim(p_message))<2 then raise exception'MESSAGE_TOO_SHORT'using errcode='P0001';end if;insert into public.support_ticket_messages(ticket_id,author_user_id,message,is_internal)values(p_id,(select auth.uid()),p_message,p_internal)returning id into v_id;if not p_internal then update public.support_tickets set status=case when v_staff then'awaiting_user'::public.support_status else'awaiting_support'::public.support_status end,updated_at=now()where id=p_id;end if;perform private.audit_platform(case when p_internal then'SUPPORT_INTERNAL_NOTE_ADDED'else'SUPPORT_REPLY_ADDED'end,'support_ticket',p_id);return v_id;end$$;

create function public.reopen_support_ticket(p_id uuid)returns void language plpgsql security definer set search_path=''as $$begin if not coalesce((select(value#>>'{}')::boolean from public.platform_config where key='support_enabled'),true)then raise exception'SUPPORT_DISABLED'using errcode='P0001';end if;update public.support_tickets set status='open',closed_at=null,updated_at=now()where id=p_id and user_id=(select auth.uid())and status in('resolved','closed')and updated_at>now()-interval'7 days';if not found then raise exception'REOPEN_NOT_ALLOWED'using errcode='P0001';end if;perform private.audit_platform('SUPPORT_TICKET_REOPENED','support_ticket',p_id);end$$;

create function public.create_platform_announcement(p_title text,p_body text,p_severity public.announcement_severity,p_target text,p_starts_at timestamptz,p_ends_at timestamptz,p_published boolean,p_confirmation text default null)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;if p_severity='critical'and(p_confirmation<>'CONFIRM'or not public.is_platform_admin())then raise exception'EXPLICIT_SUPER_ADMIN_CONFIRMATION_REQUIRED'using errcode='42501';end if;insert into public.platform_announcements(title,body,severity,target,starts_at,ends_at,published,created_by)values(p_title,p_body,p_severity,p_target,p_starts_at,p_ends_at,p_published,(select auth.uid()))returning id into v_id;perform private.audit_platform('PLATFORM_ANNOUNCEMENT_CREATED','platform_announcement',v_id,jsonb_build_object('severity',p_severity,'published',p_published));return v_id;end$$;

create function public.set_platform_announcement_published(p_id uuid,p_published boolean)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;update public.platform_announcements set published=p_published where id=p_id;if not found then raise exception'ANNOUNCEMENT_NOT_FOUND'using errcode='P0001';end if;perform private.audit_platform(case when p_published then'PLATFORM_ANNOUNCEMENT_PUBLISHED'else'PLATFORM_ANNOUNCEMENT_UNPUBLISHED'end,'platform_announcement',p_id);end$$;

create function public.create_tournament_announcement(p_tournament uuid,p_title text,p_body text,p_severity public.announcement_severity,p_target text,p_starts_at timestamptz,p_ends_at timestamptz,p_published boolean)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not(public.is_platform_moderator()or public.is_tournament_role(p_tournament,'organizer'))then raise exception'TOURNAMENT_AUTHORITY_REQUIRED'using errcode='42501';end if;insert into public.tournament_announcements(tournament_id,title,body,severity,target,starts_at,ends_at,published,created_by)values(p_tournament,p_title,p_body,p_severity,p_target,p_starts_at,p_ends_at,p_published,(select auth.uid()))returning id into v_id;perform private.audit_platform('TOURNAMENT_ANNOUNCEMENT_CREATED','tournament_announcement',v_id,jsonb_build_object('tournament_id',p_tournament));return v_id;end$$;

create function public.confirm_account_deactivation(p_confirmation text,p_reason text)returns void language plpgsql security definer set search_path=''as $$begin if p_confirmation<>'DEACTIVATE'then raise exception'EXPLICIT_CONFIRMATION_REQUIRED'using errcode='P0001';end if;perform public.deactivate_own_account(p_reason);end$$;

revoke all on function public.add_moderation_case_note(uuid,text),public.update_support_ticket(uuid,public.support_status,public.case_severity,uuid),public.reply_support_ticket(uuid,text,boolean),public.reopen_support_ticket(uuid),public.create_platform_announcement(text,text,public.announcement_severity,text,timestamptz,timestamptz,boolean,text),public.set_platform_announcement_published(uuid,boolean),public.create_tournament_announcement(uuid,text,text,public.announcement_severity,text,timestamptz,timestamptz,boolean),public.confirm_account_deactivation(text,text)from public,anon;
grant execute on function public.add_moderation_case_note(uuid,text),public.update_support_ticket(uuid,public.support_status,public.case_severity,uuid),public.reply_support_ticket(uuid,text,boolean),public.reopen_support_ticket(uuid),public.create_platform_announcement(text,text,public.announcement_severity,text,timestamptz,timestamptz,boolean,text),public.set_platform_announcement_published(uuid,boolean),public.create_tournament_announcement(uuid,text,text,public.announcement_severity,text,timestamptz,timestamptz,boolean),public.confirm_account_deactivation(text,text)to authenticated;
create index reports_recent_idx on public.reports(created_at desc);
create index moderation_cases_recent_idx on public.moderation_cases(created_at desc);
create index support_tickets_recent_idx on public.support_tickets(updated_at desc);
