create type public.platform_admin_role as enum('super_admin','platform_moderator','support_agent');
create type public.platform_admin_status as enum('active','suspended','revoked');
create type public.organizer_operational_status as enum('pending','verified','restricted','suspended','revoked','rejected');
create type public.report_status as enum('submitted','triaged','under_review','awaiting_information','resolved','dismissed','escalated');
create type public.case_status as enum('open','under_review','pending_approval','resolved','dismissed');
create type public.case_severity as enum('low','medium','high','critical');
create type public.sanction_scope as enum('platform','tournament','registration','captain_access','organizer_access');
create type public.sanction_type as enum('warning','temporary_suspension','indefinite_suspension','ban','registration_restriction','captain_restriction','organizer_restriction','player_removal','team_removal','match_forfeit');
create type public.moderation_appeal_status as enum('submitted','under_review','approved','rejected','withdrawn');
create type public.support_status as enum('open','awaiting_support','awaiting_user','resolved','closed');
create type public.support_category as enum('account','tournament','payment_future','technical','bug','moderation','other');
create type public.announcement_severity as enum('info','notice','warning','critical');

create table public.platform_admins(user_id uuid primary key references public.profiles(id),role public.platform_admin_role not null,status public.platform_admin_status not null default'active',granted_by uuid references public.profiles(id),granted_at timestamptz not null default now(),revoked_at timestamptz);
create table public.organizer_verifications(user_id uuid primary key references public.profiles(id),status public.organizer_operational_status not null default'pending',requested_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by uuid references public.profiles(id),notes text,updated_at timestamptz not null default now());
create table public.reports(id uuid primary key default gen_random_uuid(),reporter_user_id uuid not null references public.profiles(id),reported_user_id uuid references public.profiles(id),tournament_id uuid references public.tournaments(id),match_id uuid references public.matches(id),report_type text not null check(report_type in('harassment','cheating','smurfing','account_sharing','false_information','no_show','unsportsmanlike_conduct','organizer_misconduct','spam','other')),reason text not null,description text not null,evidence_path text,status public.report_status not null default'submitted',priority public.case_severity not null default'medium',assigned_to uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),resolved_at timestamptz);
create table public.moderation_cases(id uuid primary key default gen_random_uuid(),report_id uuid references public.reports(id),subject_user_id uuid not null references public.profiles(id),tournament_id uuid references public.tournaments(id),case_type text not null,status public.case_status not null default'open',severity public.case_severity not null default'medium',assigned_to uuid references public.profiles(id),summary text not null,resolution text,revision bigint not null default 0,created_at timestamptz not null default now(),resolved_at timestamptz);
create table public.moderation_case_notes(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.moderation_cases(id) on delete cascade,author_user_id uuid not null references public.profiles(id),note text not null,created_at timestamptz not null default now());
create table public.sanctions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),case_id uuid references public.moderation_cases(id),tournament_id uuid references public.tournaments(id),scope public.sanction_scope not null,sanction_type public.sanction_type not null,reason text not null,starts_at timestamptz not null default now(),expires_at timestamptz,active boolean not null default true,issued_by uuid not null references public.profiles(id),revoked_by uuid references public.profiles(id),revoked_at timestamptz,created_at timestamptz not null default now(),check((scope='tournament')=(tournament_id is not null)),check(expires_at is null or expires_at>starts_at));
create unique index sanctions_one_active_equivalent on public.sanctions(user_id,scope,sanction_type,coalesce(tournament_id,'00000000-0000-0000-0000-000000000000'::uuid))where active and revoked_at is null;
create table public.moderation_appeals(id uuid primary key default gen_random_uuid(),sanction_id uuid not null references public.sanctions(id),user_id uuid not null references public.profiles(id),reason text not null,evidence_path text,status public.moderation_appeal_status not null default'submitted',reviewed_by uuid references public.profiles(id),resolution text,created_at timestamptz not null default now(),resolved_at timestamptz,unique(sanction_id,user_id));
create table public.support_tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),category public.support_category not null,subject text not null,status public.support_status not null default'open',priority public.case_severity not null default'medium',assigned_to uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz);
create table public.support_ticket_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete cascade,author_user_id uuid not null references public.profiles(id),message text not null,is_internal boolean not null default false,created_at timestamptz not null default now());
create table public.platform_announcements(id uuid primary key default gen_random_uuid(),title text not null,body text not null,severity public.announcement_severity not null default'info',target text not null default'all'check(target in('all','players','captains','organizers','spectators','admins')),starts_at timestamptz not null default now(),ends_at timestamptz,published boolean not null default false,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),check(ends_at is null or ends_at>starts_at));
create table public.tournament_announcements(id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,title text not null,body text not null,severity public.announcement_severity not null default'info',target text not null default'all'check(target in('all','players','captains','organizers','spectators')),published boolean not null default false,starts_at timestamptz not null default now(),ends_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.tournament_rule_versions(id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id),version integer not null check(version>0),content text not null,effective_at timestamptz not null default now(),requires_reacceptance boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(tournament_id,version));
alter table public.tournaments add column active_rule_version_id uuid references public.tournament_rule_versions(id);
create table public.rule_acceptances(user_id uuid not null references public.profiles(id),tournament_id uuid not null references public.tournaments(id),rule_version_id uuid not null references public.tournament_rule_versions(id),accepted_at timestamptz not null default now(),primary key(user_id,rule_version_id));
create table public.legal_acceptances(user_id uuid not null references public.profiles(id),terms_version text not null,privacy_version text not null,accepted_at timestamptz not null default now(),primary key(user_id,terms_version,privacy_version));
create table public.platform_config(key text primary key,value jsonb not null,description text not null,updated_by uuid references public.profiles(id),updated_at timestamptz not null default now(),check(key in('registrations_enabled','maintenance_mode','new_tournament_creation_enabled','support_enabled')));
insert into public.platform_config(key,value,description)values('registrations_enabled','true','Allow tournament registration'),('maintenance_mode','false','Disable critical participant mutations'),('new_tournament_creation_enabled','true','Allow tournament creation'),('support_enabled','true','Allow support tickets');
create table public.security_events(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id),event_type text not null,severity public.case_severity not null default'low',tournament_id uuid references public.tournaments(id),summary text not null,details jsonb not null default'{}',reviewed_at timestamptz,reviewed_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.abuse_signals(id uuid primary key default gen_random_uuid(),subject_user_id uuid references public.profiles(id),signal_type text not null,score numeric not null default 1,evidence_count integer not null default 1,metadata jsonb not null default'{}',created_at timestamptz not null default now());
create table public.job_health(job_name text primary key,last_success_at timestamptz,last_failure_at timestamptz,last_duration_ms integer,status text not null check(status in('unknown','healthy','degraded','failed')),message text,updated_at timestamptz not null default now());
create table public.retention_policies(category text primary key,retention_days integer,legal_basis text not null,automatic_deletion boolean not null default false,updated_at timestamptz not null default now());
insert into public.retention_policies values('public_tournament_history',null,'legitimate platform history',false,now()),('audit_logs',2555,'security and accountability',false,now()),('moderation_evidence',365,'case handling',false,now()),('support_tickets',730,'support operations',false,now()),('account_data',null,'service provision',false,now());
create table public.account_operational_status(user_id uuid primary key references public.profiles(id),deactivated_at timestamptz,deactivated_by uuid references public.profiles(id),reason text,updated_at timestamptz not null default now());
create table public.privacy_requests(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),request_type text not null check(request_type in('access','deletion')),status text not null default'submitted'check(status in('submitted','processing','completed','rejected')),created_at timestamptz not null default now(),resolved_at timestamptz);
create table public.sensitive_action_approvals(id uuid primary key default gen_random_uuid(),action_type text not null,payload jsonb not null,requested_by uuid not null references public.profiles(id),status text not null default'pending'check(status in('pending','approved','rejected')),reviewed_by uuid references public.profiles(id),created_at timestamptz not null default now(),reviewed_at timestamptz,check(reviewed_by is null or reviewed_by<>requested_by));

create index reports_queue_idx on public.reports(status,priority,assigned_to,created_at);create index cases_queue_idx on public.moderation_cases(status,severity,assigned_to,created_at);create index sanctions_user_active_idx on public.sanctions(user_id,active,expires_at,scope);create index support_queue_idx on public.support_tickets(status,priority,assigned_to,updated_at);create index security_events_queue_idx on public.security_events(reviewed_at,severity,created_at);create index announcements_active_idx on public.platform_announcements(published,starts_at,ends_at);create index audit_search_idx on public.audit_events(event_type,created_at desc);create index audit_recent_idx on public.audit_events(created_at desc);

create function public.is_platform_admin()returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.platform_admins where user_id=(select auth.uid())and role='super_admin'and status='active')$$;
create function public.is_platform_moderator()returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.platform_admins where user_id=(select auth.uid())and role in('super_admin','platform_moderator')and status='active')$$;
create function public.is_support_agent()returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.platform_admins where user_id=(select auth.uid())and role in('super_admin','support_agent')and status='active')$$;
create function private.has_active_sanction(p_user uuid,p_scope public.sanction_scope,p_tournament uuid default null)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.sanctions s where s.user_id=p_user and s.active and s.revoked_at is null and s.starts_at<=now()and(s.expires_at is null or s.expires_at>now())and s.sanction_type<>'warning'and((s.scope='platform'and s.sanction_type in('temporary_suspension','indefinite_suspension','ban'))or(s.scope=p_scope and s.scope<>'tournament')or(s.scope='tournament'and p_scope='tournament'and s.tournament_id=p_tournament)))$$;
create function public.get_own_active_sanctions()returns table(id uuid,scope public.sanction_scope,sanction_type public.sanction_type,reason text,starts_at timestamptz,expires_at timestamptz,tournament_id uuid,appeal_eligible boolean)language sql stable security definer set search_path=''as $$select s.id,s.scope,s.sanction_type,s.reason,s.starts_at,s.expires_at,s.tournament_id,not exists(select 1 from public.moderation_appeals a where a.sanction_id=s.id)from public.sanctions s where s.user_id=(select auth.uid())and s.active and s.revoked_at is null and(s.expires_at is null or s.expires_at>now())$$;
create function private.audit_platform(p_event text,p_entity text,p_id uuid,p_payload jsonb default'{}')returns void language sql security definer set search_path=''as $$insert into public.audit_events(actor_user_id,event_type,entity_type,entity_id,payload)values((select auth.uid()),p_event,p_entity,p_id,p_payload)$$;
create or replace function public.is_tournament_role(tid uuid,wanted public.tournament_role)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.tournament_members m join public.tournament_member_roles r on r.member_id=m.id where m.tournament_id=tid and m.user_id=(select auth.uid())and m.status='active'and r.role=wanted)and not private.has_active_sanction((select auth.uid()),'platform',tid)and(wanted<>'organizer'or not private.has_active_sanction((select auth.uid()),'organizer_access',tid))and(wanted<>'captain'or not private.has_active_sanction((select auth.uid()),'captain_access',tid))$$;

create function public.manage_platform_admin(p_user uuid,p_role public.platform_admin_role,p_grant boolean)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_platform_admin()then raise exception'PLATFORM_ADMIN_REQUIRED'using errcode='42501';end if;if p_grant then insert into public.platform_admins(user_id,role,status,granted_by)values(p_user,p_role,'active',(select auth.uid()))on conflict(user_id)do update set role=excluded.role,status='active',granted_by=(select auth.uid()),granted_at=now(),revoked_at=null;perform private.audit_platform('PLATFORM_ROLE_GRANTED','platform_admin',p_user,jsonb_build_object('role',p_role));else update public.platform_admins set status='revoked',revoked_at=now()where user_id=p_user;perform private.audit_platform('PLATFORM_ROLE_REVOKED','platform_admin',p_user);end if;end$$;
create function public.issue_sanction(p_user uuid,p_case uuid,p_tournament uuid,p_scope public.sanction_scope,p_type public.sanction_type,p_reason text,p_expires timestamptz default null)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if p_scope in('platform','registration','captain_access','organizer_access')and not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;if p_scope='tournament'and not(public.is_platform_moderator()or public.is_tournament_role(p_tournament,'organizer')or public.is_tournament_role(p_tournament,'referee'))then raise exception'TOURNAMENT_AUTHORITY_REQUIRED'using errcode='42501';end if;if p_type='ban'and not public.is_platform_admin()then raise exception'SUPER_ADMIN_REQUIRED'using errcode='42501';end if;insert into public.sanctions(user_id,case_id,tournament_id,scope,sanction_type,reason,expires_at,issued_by)values(p_user,p_case,p_tournament,p_scope,p_type,p_reason,p_expires,(select auth.uid()))returning id into v_id;perform private.audit_platform('SANCTION_ISSUED','sanction',v_id,jsonb_build_object('scope',p_scope,'type',p_type,'user_id',p_user));return v_id;end$$;
create function public.revoke_sanction(p_id uuid,p_reason text)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;update public.sanctions set active=false,revoked_by=(select auth.uid()),revoked_at=now()where id=p_id and active;perform private.audit_platform('SANCTION_REVOKED','sanction',p_id,jsonb_build_object('reason',p_reason));end$$;
create function public.submit_moderation_appeal(p_sanction uuid,p_reason text,p_evidence_path text default null)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not exists(select 1 from public.sanctions where id=p_sanction and user_id=(select auth.uid())and active)then raise exception'APPEAL_NOT_ALLOWED'using errcode='42501';end if;insert into public.moderation_appeals(sanction_id,user_id,reason,evidence_path)values(p_sanction,(select auth.uid()),p_reason,p_evidence_path)returning id into v_id;perform private.audit_platform('SANCTION_APPEAL_SUBMITTED','moderation_appeal',v_id);return v_id;end$$;
create function public.resolve_moderation_appeal(p_id uuid,p_approve boolean,p_resolution text)returns boolean language plpgsql security definer set search_path=''as $$declare v_s public.sanctions%rowtype;begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;select s.*into v_s from public.moderation_appeals a join public.sanctions s on s.id=a.sanction_id where a.id=p_id for update;if not found then return false;end if;if v_s.issued_by=(select auth.uid())and v_s.sanction_type='ban'then raise exception'INDEPENDENT_REVIEW_REQUIRED'using errcode='42501';end if;update public.moderation_appeals set status=(case when p_approve then'approved'else'rejected'end)::public.moderation_appeal_status,reviewed_by=(select auth.uid()),resolution=p_resolution,resolved_at=now()where id=p_id and status not in('approved','rejected');if not found then return false;end if;if p_approve then update public.sanctions set active=false,revoked_by=(select auth.uid()),revoked_at=now()where id=v_s.id;end if;perform private.audit_platform(case when p_approve then'SANCTION_APPEAL_APPROVED'else'SANCTION_APPEAL_REJECTED'end,'moderation_appeal',p_id);return true;end$$;
create function public.set_platform_config(p_key text,p_value jsonb,p_confirmation text)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_platform_admin()then raise exception'SUPER_ADMIN_REQUIRED'using errcode='42501';end if;if p_key='maintenance_mode'and p_confirmation<>'CONFIRM'then raise exception'EXPLICIT_CONFIRMATION_REQUIRED'using errcode='P0001';end if;update public.platform_config set value=p_value,updated_by=(select auth.uid()),updated_at=now()where key=p_key;perform private.audit_platform(case when p_key='maintenance_mode'then'MAINTENANCE_MODE_CHANGED'else'PLATFORM_CONFIG_CHANGED'end,'platform_config',null,jsonb_build_object('key',p_key,'value',p_value));end$$;
create function public.publish_rule_version(p_tournament uuid,p_content text,p_requires_reacceptance boolean default true)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not(public.is_platform_admin()or public.is_tournament_role(p_tournament,'organizer'))then raise exception'ORGANIZER_REQUIRED'using errcode='42501';end if;insert into public.tournament_rule_versions(tournament_id,version,content,requires_reacceptance,created_by)select p_tournament,coalesce(max(version),0)+1,p_content,p_requires_reacceptance,(select auth.uid())from public.tournament_rule_versions where tournament_id=p_tournament returning id into v_id;update public.tournaments set active_rule_version_id=v_id where id=p_tournament;perform private.audit_platform('RULE_VERSION_PUBLISHED','tournament_rule_version',v_id);return v_id;end$$;
create function public.accept_tournament_rules(p_tournament uuid,p_version uuid)returns void language plpgsql security definer set search_path=''as $$begin if not exists(select 1 from public.tournament_rule_versions where id=p_version and tournament_id=p_tournament)then raise exception'INVALID_RULE_VERSION'using errcode='P0001';end if;insert into public.rule_acceptances values((select auth.uid()),p_tournament,p_version,now())on conflict do nothing;end$$;
create function public.request_organizer_verification()returns void language plpgsql security definer set search_path=''as $$begin insert into public.organizer_verifications(user_id,status)values((select auth.uid()),'pending')on conflict(user_id)do update set status='pending',requested_at=now(),reviewed_at=null,reviewed_by=null,notes=null,updated_at=now()where public.organizer_verifications.status in('rejected','revoked');end$$;
create function public.review_organizer(p_user uuid,p_status public.organizer_operational_status,p_notes text,p_confirmation text default null)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;if p_status='revoked'and(not public.is_platform_admin()or p_confirmation<>'CONFIRM')then raise exception'EXPLICIT_SUPER_ADMIN_CONFIRMATION_REQUIRED'using errcode='42501';end if;insert into public.organizer_verifications(user_id,status,reviewed_at,reviewed_by,notes)values(p_user,p_status,now(),(select auth.uid()),p_notes)on conflict(user_id)do update set status=excluded.status,reviewed_at=now(),reviewed_by=(select auth.uid()),notes=excluded.notes,updated_at=now();perform private.audit_platform('ORGANIZER_'||upper(p_status::text),'organizer_verification',p_user);end$$;
create function public.create_report(p_reported uuid,p_tournament uuid,p_match uuid,p_type text,p_reason text,p_description text,p_evidence_path text default null)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if length(trim(p_description))<10 then raise exception'REPORT_DESCRIPTION_TOO_SHORT'using errcode='P0001';end if;if(select count(*)from public.reports where reporter_user_id=(select auth.uid())and created_at>now()-interval'1 hour')>=10 then raise exception'RATE_LIMITED'using errcode='P0001';end if;insert into public.reports(reporter_user_id,reported_user_id,tournament_id,match_id,report_type,reason,description,evidence_path)values((select auth.uid()),p_reported,p_tournament,p_match,p_type,p_reason,p_description,p_evidence_path)returning id into v_id;perform private.audit_platform('REPORT_SUBMITTED','report',v_id);return v_id;end$$;
create function public.create_moderation_case(p_report uuid,p_subject uuid,p_tournament uuid,p_type text,p_severity public.case_severity,p_summary text)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;insert into public.moderation_cases(report_id,subject_user_id,tournament_id,case_type,severity,summary,assigned_to)values(p_report,p_subject,p_tournament,p_type,p_severity,p_summary,(select auth.uid()))returning id into v_id;update public.reports set status='under_review',assigned_to=(select auth.uid()),updated_at=now()where id=p_report;perform private.audit_platform('MODERATION_CASE_CREATED','moderation_case',v_id);return v_id;end$$;
create function public.resolve_moderation_case(p_id uuid,p_resolution text,p_revision bigint)returns boolean language plpgsql security definer set search_path=''as $$begin if not public.is_platform_moderator()then raise exception'PLATFORM_MODERATOR_REQUIRED'using errcode='42501';end if;update public.moderation_cases set status='resolved',resolution=p_resolution,resolved_at=now(),revision=revision+1 where id=p_id and revision=p_revision and status not in('resolved','dismissed');if not found then return false;end if;perform private.audit_platform('MODERATION_CASE_RESOLVED','moderation_case',p_id);return true;end$$;
create function public.create_support_ticket(p_category public.support_category,p_subject text,p_message text)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if not coalesce((select(value#>>'{}')::boolean from public.platform_config where key='support_enabled'),true)then raise exception'SUPPORT_DISABLED'using errcode='P0001';end if;if(select count(*)from public.support_tickets where user_id=(select auth.uid())and created_at>now()-interval'1 hour')>=10 then raise exception'RATE_LIMITED'using errcode='P0001';end if;insert into public.support_tickets(user_id,category,subject)values((select auth.uid()),p_category,p_subject)returning id into v_id;insert into public.support_ticket_messages(ticket_id,author_user_id,message)values(v_id,(select auth.uid()),p_message);return v_id;end$$;
create function public.close_support_ticket(p_id uuid)returns void language plpgsql security definer set search_path=''as $$begin update public.support_tickets set status='closed',closed_at=now(),updated_at=now()where id=p_id and(user_id=(select auth.uid())or public.is_support_agent());if not found then raise exception'TICKET_NOT_FOUND'using errcode='42501';end if;perform private.audit_platform('SUPPORT_TICKET_CLOSED','support_ticket',p_id);end$$;
create function public.deactivate_own_account(p_reason text)returns void language plpgsql security definer set search_path=''as $$begin insert into public.account_operational_status(user_id,deactivated_at,deactivated_by,reason)values((select auth.uid()),now(),(select auth.uid()),p_reason)on conflict(user_id)do update set deactivated_at=now(),deactivated_by=(select auth.uid()),reason=excluded.reason,updated_at=now();perform private.audit_platform('ACCOUNT_DEACTIVATED','profile',(select auth.uid()));end$$;

create function private.enforce_operational_access()returns trigger language plpgsql security definer set search_path=''as $$declare v_user uuid:=(select auth.uid());v_tid uuid;begin
 if tg_table_name='tournaments'then v_tid:=new.id;else v_tid:=new.tournament_id;end if;
 if coalesce((select(value#>>'{}')::boolean from public.platform_config where key='maintenance_mode'),false)and not public.is_platform_admin()then raise exception'MAINTENANCE_MODE'using errcode='P0001';end if;
 if v_user is not null and exists(select 1 from public.account_operational_status where user_id=v_user and deactivated_at is not null)then raise exception'ACCOUNT_DEACTIVATED'using errcode='P0001';end if;
 if tg_table_name='tournament_players'then v_user:=coalesce(v_user,(to_jsonb(new)->>'user_id')::uuid);if private.has_active_sanction(v_user,'registration',v_tid)then raise exception'REGISTRATION_RESTRICTED'using errcode='P0001';end if;end if;
 if tg_table_name='teams'and private.has_active_sanction((to_jsonb(new)->>'captain_user_id')::uuid,'captain_access',v_tid)then raise exception'CAPTAIN_ACCESS_RESTRICTED'using errcode='P0001';end if;return new;end$$;
create trigger operational_tournament_players before insert or update on public.tournament_players for each row execute function private.enforce_operational_access();
create trigger operational_teams before insert or update on public.teams for each row execute function private.enforce_operational_access();
create trigger operational_tournaments before insert or update on public.tournaments for each row execute function private.enforce_operational_access();

create view public.public_active_announcements with(security_invoker=true,security_barrier=true)as select id,title,body,severity,target,starts_at,ends_at from public.platform_announcements where published and target<>'admins'and starts_at<=now()and(ends_at is null or ends_at>now());
create view public.platform_health with(security_invoker=true,security_barrier=true)as select (select count(*)from public.tournaments where status not in('completed','cancelled'))active_tournaments,(select count(*)from public.reports where status not in('resolved','dismissed'))open_reports,(select count(*)from public.moderation_cases where status not in('resolved','dismissed'))open_cases,(select count(*)from public.support_tickets where status not in('resolved','closed'))open_support,(select count(*)from public.sanctions where active and revoked_at is null and(expires_at is null or expires_at>now()))active_sanctions,(select count(*)from public.matches where status='disputed')unresolved_disputes,(select count(*)from public.matches m left join public.competitive_rating_events e on e.match_id=m.id where m.status='completed'and m.forfeit_team_id is null and e.id is null)rating_backlog;

alter table public.platform_admins enable row level security;alter table public.organizer_verifications enable row level security;alter table public.reports enable row level security;alter table public.moderation_cases enable row level security;alter table public.moderation_case_notes enable row level security;alter table public.sanctions enable row level security;alter table public.moderation_appeals enable row level security;alter table public.support_tickets enable row level security;alter table public.support_ticket_messages enable row level security;alter table public.platform_announcements enable row level security;alter table public.tournament_announcements enable row level security;alter table public.tournament_rule_versions enable row level security;alter table public.rule_acceptances enable row level security;alter table public.legal_acceptances enable row level security;alter table public.platform_config enable row level security;alter table public.security_events enable row level security;alter table public.abuse_signals enable row level security;alter table public.job_health enable row level security;alter table public.retention_policies enable row level security;alter table public.account_operational_status enable row level security;alter table public.privacy_requests enable row level security;alter table public.sensitive_action_approvals enable row level security;
create policy platform_admin_self_read on public.platform_admins for select to authenticated using(user_id=(select auth.uid())or public.is_platform_admin());
create policy reports_owner_read on public.reports for select to authenticated using(reporter_user_id=(select auth.uid())or public.is_platform_moderator());create policy reports_owner_create on public.reports for insert to authenticated with check(reporter_user_id=(select auth.uid())and status='submitted'and priority='medium'and assigned_to is null and resolved_at is null);create policy reports_moderator_update on public.reports for update to authenticated using(public.is_platform_moderator())with check(public.is_platform_moderator());
create policy cases_moderator on public.moderation_cases for all to authenticated using(public.is_platform_moderator())with check(public.is_platform_moderator());create policy notes_moderator on public.moderation_case_notes for select to authenticated using(public.is_platform_moderator());create policy notes_append on public.moderation_case_notes for insert to authenticated with check(public.is_platform_moderator()and author_user_id=(select auth.uid()));
create policy sanctions_moderator_read on public.sanctions for select to authenticated using(public.is_platform_moderator());create policy appeals_owner_read on public.moderation_appeals for select to authenticated using(user_id=(select auth.uid())or public.is_platform_moderator());
create policy tickets_owner_read on public.support_tickets for select to authenticated using(user_id=(select auth.uid())or public.is_support_agent());create policy tickets_owner_create on public.support_tickets for insert to authenticated with check(user_id=(select auth.uid())and status='open'and priority='medium'and assigned_to is null and closed_at is null);create policy tickets_staff_update on public.support_tickets for update to authenticated using(public.is_support_agent())with check(public.is_support_agent());
create policy messages_visible on public.support_ticket_messages for select to authenticated using(public.is_support_agent()or(not is_internal and exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=(select auth.uid()))));create policy messages_write on public.support_ticket_messages for insert to authenticated with check(author_user_id=(select auth.uid())and(public.is_support_agent()or(not is_internal and exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=(select auth.uid())))));
create policy public_announcements_read on public.platform_announcements for select to anon,authenticated using(published and target<>'admins'and starts_at<=now()and(ends_at is null or ends_at>now())or public.is_platform_moderator());create policy admin_announcements_manage on public.platform_announcements for all to authenticated using(public.is_platform_moderator())with check(public.is_platform_moderator());
create policy tournament_announcements_read on public.tournament_announcements for select to anon,authenticated using(published and starts_at<=now()and(ends_at is null or ends_at>now())or public.is_tournament_role(tournament_id,'organizer')or public.is_platform_moderator());create policy tournament_announcements_manage on public.tournament_announcements for all to authenticated using(public.is_tournament_role(tournament_id,'organizer')or public.is_platform_moderator())with check(public.is_tournament_role(tournament_id,'organizer')or public.is_platform_moderator());
create policy rule_versions_read on public.tournament_rule_versions for select to authenticated using(exists(select 1 from public.tournament_members m where m.tournament_id=tournament_rule_versions.tournament_id and m.user_id=(select auth.uid()))or public.is_platform_moderator());create policy acceptance_owner on public.rule_acceptances for select to authenticated using(user_id=(select auth.uid())or public.is_platform_moderator());create policy legal_owner on public.legal_acceptances for select to authenticated using(user_id=(select auth.uid())or public.is_platform_admin());create policy legal_insert on public.legal_acceptances for insert to authenticated with check(user_id=(select auth.uid()));
create policy config_admin on public.platform_config for select to authenticated using(public.is_platform_admin());create policy organizer_verification_self_read on public.organizer_verifications for select to authenticated using(public.is_platform_moderator()or user_id=(select auth.uid()));create policy organizer_verification_admin_update on public.organizer_verifications for update to authenticated using(public.is_platform_moderator())with check(public.is_platform_moderator());
create policy security_admin on public.security_events for select to authenticated using(public.is_platform_moderator());create policy abuse_admin on public.abuse_signals for select to authenticated using(public.is_platform_moderator());create policy jobs_admin on public.job_health for select to authenticated using(public.is_platform_admin());create policy retention_admin on public.retention_policies for select to authenticated using(public.is_platform_admin());create policy account_self on public.account_operational_status for select to authenticated using(user_id=(select auth.uid())or public.is_platform_moderator());create policy privacy_owner on public.privacy_requests for all to authenticated using(user_id=(select auth.uid())or public.is_support_agent())with check(user_id=(select auth.uid())or public.is_support_agent());create policy approvals_admin on public.sensitive_action_approvals for all to authenticated using(public.is_platform_admin())with check(public.is_platform_admin());
create policy platform_audit_read on public.audit_events for select to authenticated using(public.is_platform_moderator());

grant select,insert on public.reports,public.support_tickets,public.support_ticket_messages,public.legal_acceptances,public.privacy_requests to authenticated;
grant select on public.platform_admins,public.organizer_verifications,public.moderation_cases,public.moderation_case_notes,public.sanctions,public.moderation_appeals,public.platform_announcements,public.tournament_announcements,public.tournament_rule_versions,public.rule_acceptances,public.platform_config,public.security_events,public.abuse_signals,public.job_health,public.retention_policies,public.account_operational_status,public.sensitive_action_approvals,public.platform_health to authenticated;
grant insert on public.moderation_case_notes to authenticated;grant insert,update,delete on public.platform_announcements,public.tournament_announcements to authenticated;
grant update on public.reports,public.support_tickets to authenticated;grant select on public.public_active_announcements to anon,authenticated;
revoke all on function private.has_active_sanction(uuid,public.sanction_scope,uuid),private.audit_platform(text,text,uuid,jsonb),private.enforce_operational_access()from public,anon,authenticated;
revoke all on function public.manage_platform_admin(uuid,public.platform_admin_role,boolean),public.issue_sanction(uuid,uuid,uuid,public.sanction_scope,public.sanction_type,text,timestamptz),public.revoke_sanction(uuid,text),public.submit_moderation_appeal(uuid,text,text),public.resolve_moderation_appeal(uuid,boolean,text),public.set_platform_config(text,jsonb,text),public.publish_rule_version(uuid,text,boolean),public.accept_tournament_rules(uuid,uuid),public.get_own_active_sanctions()from public,anon;
grant execute on function public.is_platform_admin(),public.is_platform_moderator(),public.is_support_agent(),public.get_own_active_sanctions(),public.submit_moderation_appeal(uuid,text,text),public.accept_tournament_rules(uuid,uuid)to authenticated;
grant execute on function public.manage_platform_admin(uuid,public.platform_admin_role,boolean),public.issue_sanction(uuid,uuid,uuid,public.sanction_scope,public.sanction_type,text,timestamptz),public.revoke_sanction(uuid,text),public.resolve_moderation_appeal(uuid,boolean,text),public.set_platform_config(text,jsonb,text),public.publish_rule_version(uuid,text,boolean)to authenticated;
revoke all on function public.request_organizer_verification(),public.review_organizer(uuid,public.organizer_operational_status,text,text),public.create_report(uuid,uuid,uuid,text,text,text,text),public.create_moderation_case(uuid,uuid,uuid,text,public.case_severity,text),public.resolve_moderation_case(uuid,text,bigint),public.create_support_ticket(public.support_category,text,text),public.close_support_ticket(uuid),public.deactivate_own_account(text)from public,anon;
grant execute on function public.request_organizer_verification(),public.create_report(uuid,uuid,uuid,text,text,text,text),public.create_support_ticket(public.support_category,text,text),public.close_support_ticket(uuid),public.deactivate_own_account(text)to authenticated;
grant execute on function public.review_organizer(uuid,public.organizer_operational_status,text,text),public.create_moderation_case(uuid,uuid,uuid,text,public.case_severity,text),public.resolve_moderation_case(uuid,text,bigint)to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('moderation-evidence','moderation-evidence',false,10485760,array['image/png','image/jpeg','application/pdf'])on conflict(id)do nothing;
create policy moderation_evidence_upload on storage.objects for insert to authenticated with check(bucket_id='moderation-evidence'and(storage.foldername(name))[1]=(select auth.uid())::text);
create policy moderation_evidence_owner_read on storage.objects for select to authenticated using(bucket_id='moderation-evidence'and((storage.foldername(name))[1]=(select auth.uid())::text or public.is_platform_moderator()));
