alter table public.external_provider_health add column circuit_state text not null default'closed' check(circuit_state in('closed','open','half_open')),add column next_retry_at timestamptz,add column recent_error_count integer not null default 0 check(recent_error_count>=0),add column rate_limit_count integer not null default 0 check(rate_limit_count>=0);

create table public.match_external_link_history(id uuid primary key default gen_random_uuid(),match_external_link_id uuid not null references public.match_external_links(id),match_game_id uuid not null references public.match_games(id),old_dota_match_id bigint not null,new_dota_match_id bigint not null,reason text not null check(length(trim(reason)) between 8 and 500),changed_by uuid not null references public.profiles(id),changed_at timestamptz not null default now());
alter table public.match_external_link_history enable row level security;
create policy relink_history_official_read on public.match_external_link_history for select to authenticated using(public.is_platform_moderator() or exists(select 1 from public.match_games g join public.matches m on m.id=g.match_id where g.id=match_game_id and(public.is_tournament_role(m.tournament_id,'organizer')or public.is_tournament_role(m.tournament_id,'referee'))));
grant select on public.match_external_link_history to authenticated;

create function public.record_provider_state(p_provider public.external_provider,p_state text,p_failures integer,p_open_until timestamptz,p_event text)returns void language plpgsql security definer set search_path=''as $$declare v_old text;begin if p_state not in('closed','open','half_open')or p_event not in('failure','rate_limited','recovered','success')then raise exception'INVALID_PROVIDER_STATE'using errcode='P0001';end if;select circuit_state into v_old from public.external_provider_health where provider=p_provider for update;update public.external_provider_health set circuit_state=p_state,status=case when p_state='closed'then'healthy'when p_state='open'then'down'else'degraded'end,consecutive_failures=p_failures,circuit_open_until=p_open_until,next_retry_at=p_open_until,last_success_at=case when p_event in('success','recovered')then now()else last_success_at end,last_failure_at=case when p_event in('failure','rate_limited')then now()else last_failure_at end,recent_error_count=recent_error_count+(p_event='failure')::int,rate_limit_count=rate_limit_count+(p_event='rate_limited')::int,last_error_code=case when p_event='rate_limited'then'PROVIDER_RATE_LIMITED'when p_event='failure'then'PROVIDER_UNAVAILABLE'else null end,updated_at=now()where provider=p_provider;if(v_old='closed'and p_state='open')or(v_old in('open','half_open')and p_state='closed')then insert into public.audit_events(actor_user_id,event_type,entity_type,payload)values(null,case when p_state='closed'then'PROVIDER_RECOVERED'else'PROVIDER_DEGRADED'end,'external_provider',jsonb_build_object('provider',p_provider,'state',p_state));end if;end$$;
revoke all on function public.record_provider_state(public.external_provider,text,integer,timestamptz,text)from public,anon,authenticated;grant execute on function public.record_provider_state(public.external_provider,text,integer,timestamptz,text)to service_role;

create function public.relink_external_dota_match(p_link_id uuid,p_new_match_id bigint,p_reason text)returns uuid language plpgsql security definer set search_path=''as $$declare v_old bigint;v_game uuid;v_tid uuid;begin if p_new_match_id<=0 then raise exception'INVALID_MATCH_ID'using errcode='P0001';end if;if length(trim(p_reason))<8 then raise exception'RELINK_REASON_REQUIRED'using errcode='P0001';end if;select l.dota_match_id,l.match_game_id,m.tournament_id into v_old,v_game,v_tid from public.match_external_links l join public.match_games g on g.id=l.match_game_id join public.matches m on m.id=g.match_id where l.id=p_link_id for update of l;if v_old is null then raise exception'MATCH_NOT_FOUND'using errcode='P0001';end if;if not(public.is_platform_moderator()or public.is_tournament_role(v_tid,'organizer')or public.is_tournament_role(v_tid,'referee'))then raise exception'UNAUTHORIZED_REFEREE'using errcode='P0001';end if;insert into public.dota_matches(match_id,source_hash)values(p_new_match_id,md5(p_new_match_id::text)||md5('pending'))on conflict do nothing;insert into public.match_external_link_history(match_external_link_id,match_game_id,old_dota_match_id,new_dota_match_id,reason,changed_by)values(p_link_id,v_game,v_old,p_new_match_id,trim(p_reason),(select auth.uid()));update public.match_external_links set dota_match_id=p_new_match_id,reconciliation_state='pending',radiant_team_id=null,dire_team_id=null,external_winner_team_id=null,result_agrees=null,participant_summary='{}'where id=p_link_id;update public.match_games set external_match_id=p_new_match_id::text where id=v_game;insert into public.external_sync_jobs(provider,job_type,dedupe_key,external_match_id,created_by)values('opendota','match_import','match:'||p_new_match_id,p_new_match_id,(select auth.uid()))on conflict do nothing;insert into public.audit_events(tournament_id,actor_user_id,event_type,entity_type,entity_id,payload)values(v_tid,(select auth.uid()),'EXTERNAL_MATCH_RELINKED','match_game',v_game,jsonb_build_object('old_match_id',v_old,'new_match_id',p_new_match_id,'reason',trim(p_reason)));return p_link_id;exception when unique_violation then raise exception'MATCH_ALREADY_LINKED'using errcode='P0001';end$$;
revoke all on function public.relink_external_dota_match(uuid,bigint,text)from public,anon;grant execute on function public.relink_external_dota_match(uuid,bigint,text)to authenticated;

create view public.public_player_dota_stats with(security_invoker=true,security_barrier=true)as select pr.public_slug,count(*)::integer games_played,count(*)filter(where mp.is_radiant=dm.radiant_win)::integer wins,count(*)filter(where mp.is_radiant<>dm.radiant_win)::integer losses,sum(mp.kills)::integer kills,sum(mp.deaths)::integer deaths,sum(mp.assists)::integer assists,round((sum(mp.kills)+sum(mp.assists))::numeric/greatest(sum(mp.deaths),1),2)kda,round(avg(mp.gpm)filter(where mp.gpm is not null),2)avg_gpm,round(avg(mp.xpm)filter(where mp.xpm is not null),2)avg_xpm,count(distinct mp.hero_id)::integer hero_diversity from public.dota_match_players mp join public.dota_matches dm on dm.match_id=mp.match_id join public.match_external_links l on l.dota_match_id=dm.match_id join public.match_games mg on mg.id=l.match_game_id join public.matches m on m.id=mg.match_id join public.player_game_accounts a on a.dota_account_id=mp.account_id join public.profiles pr on pr.id=a.player_id where m.status in('completed','forfeit')and l.reconciliation_state in('matched','result_conflict')group by pr.public_slug;
create view public.public_tournament_dota_stats with(security_invoker=true,security_barrier=true)as select t.slug tournament_slug,count(distinct l.dota_match_id)::integer imported_games,count(distinct mg.id)::integer linked_game_slots,round(avg(dm.duration_seconds)filter(where dm.duration_seconds is not null),2)avg_duration_seconds,count(*)filter(where dm.parse_state='parsed')::integer parsed_games from public.tournaments t join public.matches m on m.tournament_id=t.id join public.match_games mg on mg.match_id=m.id left join public.match_external_links l on l.match_game_id=mg.id left join public.dota_matches dm on dm.match_id=l.dota_match_id where t.status not in('draft','cancelled')group by t.slug;
grant select on public.public_player_dota_stats,public.public_tournament_dota_stats to anon,authenticated;
create view public.provider_operational_metrics with(security_invoker=true,security_barrier=true)as select h.provider,h.status,h.circuit_state,h.consecutive_failures,h.last_success_at,h.last_failure_at,h.last_error_code,h.next_retry_at,h.recent_error_count,h.rate_limit_count,(select count(*)from public.external_provider_requests r where r.provider=h.provider and r.created_at>=now()-interval'1 minute'and r.outcome<>'cache_hit')requests_minute,(select count(*)from public.external_provider_requests r where r.provider=h.provider and r.created_at>=now()-interval'1 hour'and r.outcome<>'cache_hit')requests_hour,(select count(*)from public.external_provider_requests r where r.provider=h.provider and r.created_at>=now()-interval'1 day'and r.outcome<>'cache_hit')requests_day,(select count(*)from public.external_provider_requests r where r.provider=h.provider and r.created_at>=now()-interval'1 day'and r.outcome='cache_hit')cache_hits_day,(select count(*)from public.external_sync_jobs j where j.provider=h.provider and j.status in('queued','retry_scheduled'))queue_depth from public.external_provider_health h;
grant select on public.provider_operational_metrics to authenticated;
drop policy game_accounts_owner_read on public.player_game_accounts;create policy game_accounts_authorized_read on public.player_game_accounts for select to authenticated using(player_id=(select auth.uid())or public.is_platform_moderator()or exists(select 1 from public.tournament_players tp where tp.user_id=player_id and public.is_tournament_role(tp.tournament_id,'organizer')));
drop policy profile_snapshots_owner_read on public.dota_profile_snapshots;create policy profile_snapshots_authorized_read on public.dota_profile_snapshots for select to authenticated using(exists(select 1 from public.player_game_accounts a where a.id=player_game_account_id and(a.player_id=(select auth.uid())or public.is_platform_moderator()or exists(select 1 from public.tournament_players tp where tp.user_id=a.player_id and public.is_tournament_role(tp.tournament_id,'organizer')))));
create view public.organizer_dota_verification with(security_invoker=true,security_barrier=true)as select tp.tournament_id,tp.id tournament_player_id,a.dota_account_id,a.verification_status,s.provider,s.profile_visibility,s.rank_tier,s.leaderboard_rank,s.captured_at last_synced_at from public.tournament_players tp left join public.player_game_accounts a on a.player_id=tp.user_id and a.is_primary left join lateral(select x.provider,x.profile_visibility,x.rank_tier,x.leaderboard_rank,x.captured_at from public.dota_profile_snapshots x where x.player_game_account_id=a.id order by x.captured_at desc limit 1)s on true where public.is_tournament_role(tp.tournament_id,'organizer');grant select on public.organizer_dota_verification to authenticated;
create function private.is_public_dota_match(p_match_id bigint)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.match_external_links l join public.match_games g on g.id=l.match_game_id join public.matches m on m.id=g.match_id where l.dota_match_id=p_match_id and m.status in('completed','forfeit')and l.reconciliation_state in('matched','result_conflict'))$$;create function private.is_public_match_game(p_game_id uuid)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.match_games g join public.matches m on m.id=g.match_id where g.id=p_game_id and m.status in('completed','forfeit'))$$;
revoke all on function private.is_public_dota_match(bigint),private.is_public_match_game(uuid)from public;grant execute on function private.is_public_dota_match(bigint),private.is_public_match_game(uuid)to anon,authenticated;
drop policy matches_public_read on public.dota_matches;create policy matches_public_read on public.dota_matches for select to anon,authenticated using(private.is_public_dota_match(match_id));drop policy match_players_public_read on public.dota_match_players;create policy match_players_public_read on public.dota_match_players for select to anon,authenticated using(private.is_public_dota_match(match_id));drop policy links_public_read on public.match_external_links;create policy links_public_read on public.match_external_links for select to anon,authenticated using(private.is_public_match_game(match_game_id));
alter view public.public_dota_match_stats set(security_invoker=false);alter view public.public_player_dota_stats set(security_invoker=false);alter view public.public_tournament_dota_stats set(security_invoker=false);
