create type public.competition_format as enum ('round_robin','groups','single_elimination');
create type public.competition_stage_type as enum ('group','league','knockout','grand_final');
create type public.match_status as enum ('scheduled','check_in','ready','live','awaiting_confirmation','disputed','completed','forfeit','cancelled','rescheduled');
create type public.result_submission_status as enum ('pending','confirmed','disputed','superseded');
create type public.dispute_status as enum ('open','resolved');

create table public.competition_settings(
 tournament_id uuid primary key references public.tournaments(id) on delete cascade,
 format public.competition_format not null,
 points_win integer not null default 3,points_draw integer not null default 1,points_loss integer not null default 0,
 allow_draws boolean not null default false,default_best_of integer not null default 3 check(default_best_of>0 and default_best_of%2=1),
 lineup_size integer not null default 5 check(lineup_size>0),advance_per_group integer not null default 2 check(advance_per_group>0),
 tiebreak_rules jsonb not null default '["points","head_to_head","game_difference","games_won"]'::jsonb,
 rules_version integer not null default 1,configured_at timestamptz not null default now(),configured_by uuid not null references public.profiles(id),
 check(points_win>=points_draw and points_draw>=points_loss),check(jsonb_typeof(tiebreak_rules)='array')
);
create table public.competition_stages(id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,name text not null,stage_type public.competition_stage_type not null,sequence_number integer not null check(sequence_number>0),is_complete boolean not null default false,created_at timestamptz not null default now(),unique(tournament_id,sequence_number));
create table public.competition_groups(id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,stage_id uuid not null references public.competition_stages(id) on delete cascade,name text not null,sequence_number integer not null check(sequence_number>0),created_at timestamptz not null default now(),unique(stage_id,name));
create table public.competition_group_teams(group_id uuid not null references public.competition_groups(id) on delete cascade,team_id uuid not null references public.teams(id) on delete cascade,seed integer not null check(seed>0),primary key(group_id,team_id),unique(group_id,seed));
create table public.matches(
 id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,stage_id uuid not null references public.competition_stages(id),group_id uuid references public.competition_groups(id),round_number integer not null check(round_number>0),match_number integer not null check(match_number>0),
 team_a_id uuid references public.teams(id),team_b_id uuid references public.teams(id),scheduled_at timestamptz,best_of integer not null check(best_of>0 and best_of%2=1),status public.match_status not null default 'scheduled',
 winner_team_id uuid references public.teams(id),loser_team_id uuid references public.teams(id),team_a_score integer check(team_a_score>=0),team_b_score integer check(team_b_score>=0),
 check_in_opens_at timestamptz,check_in_deadline timestamptz,started_at timestamptz,completed_at timestamptz,forfeit_team_id uuid references public.teams(id),forfeit_reason text,
 lobby_server_id text,lobby_name text,lobby_region text,lobby_password text,external_match_reference text,
 next_match_id uuid references public.matches(id),next_match_slot smallint check(next_match_slot in (1,2)),revision bigint not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 foreign key(tournament_id,team_a_id) references public.teams(tournament_id,id),foreign key(tournament_id,team_b_id) references public.teams(tournament_id,id),
 check(team_a_id is null or team_b_id is null or team_a_id<>team_b_id),unique(stage_id,round_number,match_number)
);
create table public.match_games(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,game_number integer not null check(game_number>0),winner_team_id uuid references public.teams(id),team_a_score integer not null default 0 check(team_a_score>=0),team_b_score integer not null default 0 check(team_b_score>=0),external_match_id text,replay_url text,started_at timestamptz,completed_at timestamptz,metadata jsonb not null default '{}'::jsonb,unique(match_id,game_number));
create table public.match_check_ins(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,team_id uuid not null references public.teams(id),checked_in_by uuid not null references public.profiles(id),checked_in_at timestamptz not null default now(),is_override boolean not null default false,unique(match_id,team_id));
create table public.match_lineups(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,team_id uuid not null references public.teams(id),confirmed_by uuid not null references public.profiles(id),confirmed_at timestamptz not null default now(),locked_at timestamptz,unique(match_id,team_id));
create table public.match_lineup_players(lineup_id uuid not null references public.match_lineups(id) on delete cascade,player_id uuid not null references public.tournament_players(id),player_ign text not null,is_substitute boolean not null default false,primary key(lineup_id,player_id));
create table public.match_result_submissions(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,submitting_team_id uuid not null references public.teams(id),submitted_by uuid not null references public.profiles(id),team_a_score integer not null check(team_a_score>=0),team_b_score integer not null check(team_b_score>=0),winner_team_id uuid not null references public.teams(id),evidence_path text,notes text,status public.result_submission_status not null default 'pending',request_id uuid not null unique,created_at timestamptz not null default now(),unique(match_id,submitting_team_id));
create table public.match_disputes(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,submission_id uuid not null references public.match_result_submissions(id),opened_by uuid not null references public.profiles(id),opening_team_id uuid not null references public.teams(id),reason text not null,evidence_path text,status public.dispute_status not null default 'open',resolution text,resolved_by uuid references public.profiles(id),created_at timestamptz not null default now(),resolved_at timestamptz,request_id uuid not null unique);
create table public.match_schedule_changes(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,old_scheduled_at timestamptz,new_scheduled_at timestamptz not null,reason text not null,changed_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.competition_notifications(id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,recipient_user_id uuid references public.profiles(id),event_type text not null,match_id uuid references public.matches(id) on delete cascade,payload jsonb not null default '{}'::jsonb,read_at timestamptz,created_at timestamptz not null default now());
create table public.competition_result_snapshots(id uuid primary key default gen_random_uuid(),tournament_id uuid not null unique references public.tournaments(id),champion_team_id uuid references public.teams(id),runner_up_team_id uuid references public.teams(id),settings jsonb not null,standings jsonb not null,matches jsonb not null,created_at timestamptz not null default now());

create index matches_schedule_idx on public.matches(tournament_id,status,scheduled_at);create index matches_stage_idx on public.matches(stage_id,round_number,match_number);create index checkins_match_idx on public.match_check_ins(match_id);create index submissions_match_idx on public.match_result_submissions(match_id,created_at);create index disputes_match_idx on public.match_disputes(match_id,status);create index notifications_recipient_idx on public.competition_notifications(recipient_user_id,read_at,created_at desc);

create function private.is_competition_official(p_tournament_id uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_tournament_role(p_tournament_id,'organizer') or public.is_tournament_role(p_tournament_id,'referee')$$;
create function private.is_match_captain(p_match_id uuid,p_team_id uuid default null) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.matches m join public.teams t on t.tournament_id=m.tournament_id and t.id in(m.team_a_id,m.team_b_id) where m.id=p_match_id and t.captain_user_id=(select auth.uid()) and (p_team_id is null or t.id=p_team_id))$$;
create function private.audit_match(p_match_id uuid,p_event text,p_payload jsonb default '{}') returns void language plpgsql security definer set search_path='' as $$declare v_tid uuid;begin select tournament_id into v_tid from public.matches where id=p_match_id;insert into public.audit_events(tournament_id,actor_user_id,event_type,entity_type,entity_id,payload)values(v_tid,(select auth.uid()),p_event,'match',p_match_id,p_payload);end$$;

create function public.configure_competition(p_tournament_id uuid,p_format public.competition_format,p_default_best_of integer default 3,p_lineup_size integer default 5,p_points_win integer default 3,p_points_draw integer default 1,p_points_loss integer default 0,p_tiebreak_rules jsonb default '["points","head_to_head","game_difference","games_won"]') returns uuid language plpgsql security definer set search_path='' as $$begin
 if not public.is_tournament_role(p_tournament_id,'organizer') then raise exception 'UNAUTHORIZED_REFEREE' using errcode='P0001';end if;
 if exists(select 1 from public.matches where tournament_id=p_tournament_id) then raise exception 'SCHEDULE_ALREADY_EXISTS' using errcode='P0001';end if;
 insert into public.competition_settings(tournament_id,format,default_best_of,lineup_size,points_win,points_draw,points_loss,tiebreak_rules,configured_by)values(p_tournament_id,p_format,p_default_best_of,p_lineup_size,p_points_win,p_points_draw,p_points_loss,p_tiebreak_rules,(select auth.uid())) on conflict(tournament_id) do update set format=excluded.format,default_best_of=excluded.default_best_of,lineup_size=excluded.lineup_size,points_win=excluded.points_win,points_draw=excluded.points_draw,points_loss=excluded.points_loss,tiebreak_rules=excluded.tiebreak_rules,configured_at=now(),configured_by=(select auth.uid());
 update public.tournaments set status='competition' where id=p_tournament_id and status in('rosters_locked','competition');
 insert into public.audit_events(tournament_id,actor_user_id,event_type,entity_type,entity_id,payload)values(p_tournament_id,(select auth.uid()),'COMPETITION_FORMAT_CONFIGURED','tournament',p_tournament_id,jsonb_build_object('format',p_format));return p_tournament_id;end$$;

create function public.create_competition_group(p_tournament_id uuid,p_name text,p_team_ids uuid[]) returns uuid language plpgsql security definer set search_path='' as $$declare v_stage uuid;v_group uuid;v_team uuid;v_seed int:=0;begin
 if not public.is_tournament_role(p_tournament_id,'organizer') then raise exception 'UNAUTHORIZED_REFEREE' using errcode='P0001';end if;
 select id into v_stage from public.competition_stages where tournament_id=p_tournament_id and stage_type='group' order by sequence_number limit 1;
 if v_stage is null then insert into public.competition_stages(tournament_id,name,stage_type,sequence_number)values(p_tournament_id,'Group Stage','group',1)returning id into v_stage;end if;
 insert into public.competition_groups(tournament_id,stage_id,name,sequence_number)values(p_tournament_id,v_stage,p_name,(select coalesce(max(sequence_number),0)+1 from public.competition_groups where stage_id=v_stage))returning id into v_group;
 foreach v_team in array p_team_ids loop v_seed:=v_seed+1;if not exists(select 1 from public.teams where id=v_team and tournament_id=p_tournament_id) then raise exception 'INVALID_TEAM' using errcode='P0001';end if;insert into public.competition_group_teams values(v_group,v_team,v_seed);end loop;return v_group;end$$;

create function public.generate_competition_schedule(p_tournament_id uuid,p_scheduled_start timestamptz default null,p_interval_minutes integer default 60) returns integer language plpgsql security definer set search_path='' as $$declare v_settings public.competition_settings%rowtype;v_stage uuid;v_count int:=0;r record;s record;v_rounds int;v_size int;v_next uuid;begin
 if not public.is_tournament_role(p_tournament_id,'organizer') then raise exception 'UNAUTHORIZED_REFEREE' using errcode='P0001';end if;if exists(select 1 from public.matches where tournament_id=p_tournament_id) then raise exception 'SCHEDULE_ALREADY_EXISTS' using errcode='P0001';end if;select * into v_settings from public.competition_settings where tournament_id=p_tournament_id;if not found then raise exception 'COMPETITION_NOT_CONFIGURED' using errcode='P0001';end if;
 if v_settings.format in('round_robin','groups') then
  if v_settings.format='round_robin' then insert into public.competition_stages(tournament_id,name,stage_type,sequence_number)values(p_tournament_id,'League','league',1)returning id into v_stage;end if;
  for r in select a.id a_id,b.id b_id,case when v_settings.format='groups' then ga.group_id end group_id,row_number()over(order by coalesce(ga.group_id,'00000000-0000-0000-0000-000000000000'),a.id,b.id) n from public.teams a join public.teams b on b.tournament_id=a.tournament_id and a.id<b.id left join public.competition_group_teams ga on ga.team_id=a.id left join public.competition_group_teams gb on gb.team_id=b.id and gb.group_id=ga.group_id where a.tournament_id=p_tournament_id and (v_settings.format='round_robin' or gb.team_id is not null) loop
   v_count:=v_count+1;if v_settings.format='groups' then select stage_id into v_stage from public.competition_groups where id=r.group_id;end if;insert into public.matches(tournament_id,stage_id,group_id,round_number,match_number,team_a_id,team_b_id,scheduled_at,best_of,check_in_opens_at,check_in_deadline)values(p_tournament_id,v_stage,r.group_id,1,v_count,r.a_id,r.b_id,p_scheduled_start+make_interval(mins=>(v_count-1)*p_interval_minutes),v_settings.default_best_of,p_scheduled_start+make_interval(mins=>(v_count-1)*p_interval_minutes-30),p_scheduled_start+make_interval(mins=>(v_count-1)*p_interval_minutes+10));end loop;
 else
  insert into public.competition_stages(tournament_id,name,stage_type,sequence_number)values(p_tournament_id,'Knockout','knockout',1)returning id into v_stage;select count(*) into v_size from public.teams where tournament_id=p_tournament_id;v_rounds:=ceil(log(2,greatest(v_size,2)))::int;
  for r in 1..v_rounds loop for s in 1..(power(2,v_rounds-r)::int) loop insert into public.matches(tournament_id,stage_id,round_number,match_number,best_of,scheduled_at)values(p_tournament_id,v_stage,r,s,v_settings.default_best_of,p_scheduled_start+make_interval(mins=>(r-1)*p_interval_minutes)) returning id into v_next;v_count:=v_count+1;end loop;end loop;
  update public.matches m set team_a_id=x.team_a,team_b_id=x.team_b from(select m2.id,(array_agg(t.id order by t.id))[m2.match_number*2-1] team_a,(array_agg(t.id order by t.id))[m2.match_number*2] team_b from public.matches m2 cross join public.teams t where m2.stage_id=v_stage and m2.round_number=1 and t.tournament_id=p_tournament_id group by m2.id,m2.match_number)x where m.id=x.id;
  update public.matches m set next_match_id=n.id,next_match_slot=case when m.match_number%2=1 then 1 else 2 end from public.matches n where m.stage_id=v_stage and n.stage_id=v_stage and n.round_number=m.round_number+1 and n.match_number=ceil(m.match_number/2.0) and m.round_number<v_rounds;
 end if;
 insert into public.audit_events(tournament_id,actor_user_id,event_type,entity_type,entity_id,payload)values(p_tournament_id,(select auth.uid()),'SCHEDULE_GENERATED','tournament',p_tournament_id,jsonb_build_object('matches',v_count,'format',v_settings.format));return v_count;end$$;

create function public.check_in_team(p_match_id uuid,p_team_id uuid,p_request_id uuid default gen_random_uuid(),p_override boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;begin select * into m from public.matches where id=p_match_id for update;if not found then raise exception 'MATCH_NOT_FOUND' using errcode='P0001';end if;if not private.is_match_captain(p_match_id,p_team_id) and not private.is_competition_official(m.tournament_id) then raise exception 'NOT_PARTICIPATING_TEAM' using errcode='P0001';end if;if p_team_id not in(m.team_a_id,m.team_b_id) then raise exception 'NOT_PARTICIPATING_TEAM' using errcode='P0001';end if;if not p_override and (m.check_in_opens_at is null or clock_timestamp()<m.check_in_opens_at) then raise exception 'CHECKIN_NOT_OPEN' using errcode='P0001';end if;if not p_override and m.check_in_deadline is not null and clock_timestamp()>m.check_in_deadline then raise exception 'CHECKIN_CLOSED' using errcode='P0001';end if;insert into public.match_check_ins(match_id,team_id,checked_in_by,is_override)values(p_match_id,p_team_id,(select auth.uid()),p_override) on conflict(match_id,team_id) do nothing;perform private.audit_match(p_match_id,'TEAM_CHECKED_IN',jsonb_build_object('team_id',p_team_id,'override',p_override));return jsonb_build_object('code','TEAM_CHECKED_IN');end$$;

create function public.confirm_match_lineup(p_match_id uuid,p_team_id uuid,p_player_ids uuid[],p_request_id uuid default gen_random_uuid()) returns uuid language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;s public.competition_settings%rowtype;v_lineup uuid;v_player uuid;begin select * into m from public.matches where id=p_match_id for update;if m.status in('completed','forfeit','cancelled') then raise exception 'MATCH_ALREADY_COMPLETED' using errcode='P0001';end if;if not private.is_match_captain(p_match_id,p_team_id) and not private.is_competition_official(m.tournament_id) then raise exception 'NOT_PARTICIPATING_TEAM' using errcode='P0001';end if;select * into s from public.competition_settings where tournament_id=m.tournament_id;if cardinality(p_player_ids)<>s.lineup_size or cardinality(p_player_ids)<>(select count(distinct x)from unnest(p_player_ids)x) then raise exception 'INVALID_LINEUP' using errcode='P0001';end if;if exists(select 1 from unnest(p_player_ids)x where not exists(select 1 from public.team_roster tr where tr.tournament_id=m.tournament_id and tr.team_id=p_team_id and tr.player_id=x and tr.is_active)) then raise exception 'INVALID_LINEUP' using errcode='P0001';end if;insert into public.match_lineups(match_id,team_id,confirmed_by)values(p_match_id,p_team_id,(select auth.uid()))returning id into v_lineup;foreach v_player in array p_player_ids loop insert into public.match_lineup_players(lineup_id,player_id,player_ign,is_substitute)select v_lineup,tp.id,tp.ign,tr.is_substitute from public.tournament_players tp join public.team_roster tr on tr.player_id=tp.id and tr.team_id=p_team_id and tr.is_active where tp.id=v_player;end loop;perform private.audit_match(p_match_id,'LINEUP_CONFIRMED',jsonb_build_object('team_id',p_team_id));return v_lineup;end$$;

create function private.validate_match_score(m public.matches,a integer,b integer) returns uuid language plpgsql stable set search_path='' as $$declare needed int:=(m.best_of/2)+1;begin if a=b or greatest(a,b)<>needed or least(a,b)<0 then raise exception 'INVALID_SCORE' using errcode='P0001';end if;return case when a>b then m.team_a_id else m.team_b_id end;end$$;
create function public.submit_match_result(p_match_id uuid,p_team_a_score integer,p_team_b_score integer,p_evidence_path text,p_notes text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;v_team uuid;v_winner uuid;v_id uuid;begin select * into m from public.matches where id=p_match_id for update;if m.status in('completed','forfeit','cancelled') then raise exception 'MATCH_ALREADY_COMPLETED' using errcode='P0001';end if;select id into v_team from public.teams where tournament_id=m.tournament_id and captain_user_id=(select auth.uid()) and id in(m.team_a_id,m.team_b_id);if v_team is null then raise exception 'NOT_PARTICIPATING_TEAM' using errcode='P0001';end if;select id into v_id from public.match_result_submissions where request_id=p_request_id;if v_id is not null then return jsonb_build_object('id',v_id,'code','DUPLICATE_REQUEST');end if;v_winner:=private.validate_match_score(m,p_team_a_score,p_team_b_score);insert into public.match_result_submissions(match_id,submitting_team_id,submitted_by,team_a_score,team_b_score,winner_team_id,evidence_path,notes,request_id)values(p_match_id,v_team,(select auth.uid()),p_team_a_score,p_team_b_score,v_winner,p_evidence_path,p_notes,p_request_id)returning id into v_id;update public.matches set status='awaiting_confirmation',revision=revision+1 where id=p_match_id;perform private.audit_match(p_match_id,'RESULT_SUBMITTED',jsonb_build_object('submission_id',v_id));return jsonb_build_object('id',v_id,'code','RESULT_SUBMITTED');exception when unique_violation then raise exception 'RESULT_ALREADY_SUBMITTED' using errcode='P0001';end$$;

create function private.advance_bracket(p_match_id uuid) returns void language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;begin select * into m from public.matches where id=p_match_id;if m.next_match_id is not null then update public.matches set team_a_id=case when m.next_match_slot=1 then m.winner_team_id else team_a_id end,team_b_id=case when m.next_match_slot=2 then m.winner_team_id else team_b_id end,revision=revision+1 where id=m.next_match_id and ((m.next_match_slot=1 and team_a_id is null)or(m.next_match_slot=2 and team_b_id is null));if found then perform private.audit_match(p_match_id,'BRACKET_ADVANCED',jsonb_build_object('next_match_id',m.next_match_id,'slot',m.next_match_slot));end if;end if;end$$;
create function private.complete_match(p_match_id uuid,p_a integer,p_b integer,p_status public.match_status default 'completed') returns void language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;v_winner uuid;begin select * into m from public.matches where id=p_match_id for update;if m.status in('completed','forfeit') then raise exception 'MATCH_ALREADY_COMPLETED' using errcode='P0001';end if;if exists(select 1 from public.match_disputes where match_id=p_match_id and status='open') then raise exception 'UNRESOLVED_DISPUTE' using errcode='P0001';end if;v_winner:=private.validate_match_score(m,p_a,p_b);update public.matches set status=p_status,team_a_score=p_a,team_b_score=p_b,winner_team_id=v_winner,loser_team_id=case when v_winner=team_a_id then team_b_id else team_a_id end,completed_at=clock_timestamp(),revision=revision+1 where id=p_match_id;update public.match_lineups set locked_at=clock_timestamp() where match_id=p_match_id;perform private.audit_match(p_match_id,'MATCH_COMPLETED',jsonb_build_object('winner_team_id',v_winner));perform private.advance_bracket(p_match_id);end$$;

create function public.respond_to_match_result(p_submission_id uuid,p_confirm boolean,p_reason text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare s public.match_result_submissions%rowtype;m public.matches%rowtype;v_team uuid;begin select * into s from public.match_result_submissions where id=p_submission_id for update;select * into m from public.matches where id=s.match_id for update;select id into v_team from public.teams where captain_user_id=(select auth.uid()) and tournament_id=m.tournament_id and id in(m.team_a_id,m.team_b_id);if v_team is null or v_team=s.submitting_team_id then raise exception 'NOT_PARTICIPATING_TEAM' using errcode='P0001';end if;if p_confirm then update public.match_result_submissions set status='confirmed' where id=s.id;perform private.complete_match(m.id,s.team_a_score,s.team_b_score);perform private.audit_match(m.id,'RESULT_CONFIRMED');return jsonb_build_object('code','RESULT_CONFIRMED');else if nullif(trim(p_reason),'') is null then raise exception 'DISPUTE_REASON_REQUIRED' using errcode='P0001';end if;insert into public.match_disputes(match_id,submission_id,opened_by,opening_team_id,reason,request_id)values(m.id,s.id,(select auth.uid()),v_team,p_reason,p_request_id)on conflict(request_id)do nothing;update public.match_result_submissions set status='disputed' where id=s.id;update public.matches set status='disputed',revision=revision+1 where id=m.id;perform private.audit_match(m.id,'RESULT_DISPUTED');return jsonb_build_object('code','RESULT_DISPUTED');end if;end$$;

create function public.resolve_match_dispute(p_dispute_id uuid,p_action text,p_team_a_score integer,p_team_b_score integer,p_reason text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare d public.match_disputes%rowtype;m public.matches%rowtype;begin select * into d from public.match_disputes where id=p_dispute_id for update;select * into m from public.matches where id=d.match_id for update;if not private.is_competition_official(m.tournament_id) then raise exception 'UNAUTHORIZED_REFEREE' using errcode='P0001';end if;if d.status='resolved' then return jsonb_build_object('code','DUPLICATE_REQUEST');end if;if nullif(trim(p_reason),'') is null then raise exception 'RESOLUTION_REASON_REQUIRED' using errcode='P0001';end if;update public.match_disputes set status='resolved',resolution=p_reason,resolved_by=(select auth.uid()),resolved_at=now() where id=d.id;if p_action in('uphold','change') then perform private.complete_match(m.id,p_team_a_score,p_team_b_score);elsif p_action='rematch' then update public.matches set status='rescheduled',team_a_score=null,team_b_score=null,winner_team_id=null,loser_team_id=null,revision=revision+1 where id=m.id;elsif p_action='cancel' then update public.matches set status='cancelled',revision=revision+1 where id=m.id;else raise exception 'INVALID_RESOLUTION' using errcode='P0001';end if;perform private.audit_match(m.id,'DISPUTE_RESOLVED',jsonb_build_object('action',p_action,'reason',p_reason));return jsonb_build_object('code','DISPUTE_RESOLVED');end$$;

create function public.award_match_forfeit(p_match_id uuid,p_forfeit_team_id uuid,p_reason text,p_request_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;v_needed int;begin select * into m from public.matches where id=p_match_id for update;if not private.is_competition_official(m.tournament_id) then raise exception 'UNAUTHORIZED_REFEREE' using errcode='P0001';end if;if p_forfeit_team_id not in(m.team_a_id,m.team_b_id)or nullif(trim(p_reason),'')is null then raise exception 'INVALID_FORFEIT' using errcode='P0001';end if;v_needed:=(m.best_of/2)+1;perform private.complete_match(p_match_id,case when p_forfeit_team_id=m.team_a_id then 0 else v_needed end,case when p_forfeit_team_id=m.team_b_id then 0 else v_needed end,'forfeit');update public.matches set forfeit_team_id=p_forfeit_team_id,forfeit_reason=p_reason where id=p_match_id;perform private.audit_match(p_match_id,'MATCH_FORFEITED',jsonb_build_object('forfeit_team_id',p_forfeit_team_id,'reason',p_reason));return jsonb_build_object('code','MATCH_FORFEITED');end$$;
create function public.reschedule_match(p_match_id uuid,p_scheduled_at timestamptz,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;begin select * into m from public.matches where id=p_match_id for update;if not private.is_competition_official(m.tournament_id) then raise exception 'UNAUTHORIZED_REFEREE' using errcode='P0001';end if;if nullif(trim(p_reason),'')is null then raise exception 'RESCHEDULE_REASON_REQUIRED' using errcode='P0001';end if;insert into public.match_schedule_changes(match_id,old_scheduled_at,new_scheduled_at,reason,changed_by)values(m.id,m.scheduled_at,p_scheduled_at,p_reason,(select auth.uid()));update public.matches set scheduled_at=p_scheduled_at,check_in_opens_at=p_scheduled_at-interval '30 minutes',check_in_deadline=p_scheduled_at+interval '10 minutes',status='rescheduled',revision=revision+1 where id=m.id;perform private.audit_match(m.id,'MATCH_RESCHEDULED',jsonb_build_object('old',m.scheduled_at,'new',p_scheduled_at,'reason',p_reason));end$$;

create view public.public_matches with(security_invoker=true,security_barrier=true)as select m.id,m.tournament_id,m.stage_id,m.group_id,m.round_number,m.match_number,m.team_a_id,m.team_b_id,m.scheduled_at,m.best_of,m.status,m.winner_team_id,m.team_a_score,m.team_b_score,m.started_at,m.completed_at,m.forfeit_team_id,s.name stage_name,s.stage_type,g.name group_name,a.name team_a_name,a.short_tag team_a_tag,b.name team_b_name,b.short_tag team_b_tag,w.name winner_name from public.matches m join public.tournaments t on t.id=m.tournament_id join public.competition_stages s on s.id=m.stage_id left join public.competition_groups g on g.id=m.group_id left join public.teams a on a.id=m.team_a_id left join public.teams b on b.id=m.team_b_id left join public.teams w on w.id=m.winner_team_id where t.status not in('draft','cancelled');
create view public.public_match_games with(security_invoker=true,security_barrier=true)as select g.id,g.match_id,g.game_number,g.winner_team_id,g.team_a_score,g.team_b_score,g.external_match_id,g.replay_url,g.started_at,g.completed_at from public.match_games g;
create view public.public_standings with(security_invoker=true,security_barrier=true)as with base as(select t.id team_id,t.tournament_id,t.name team_name,t.short_tag,m.group_id,count(m.id)filter(where m.status in('completed','forfeit')) played,count(m.id)filter(where m.winner_team_id=t.id and m.status in('completed','forfeit')) wins,count(m.id)filter(where m.loser_team_id=t.id and m.status in('completed','forfeit')) losses,coalesce(sum(case when m.team_a_id=t.id then m.team_a_score when m.team_b_id=t.id then m.team_b_score end)filter(where m.status in('completed','forfeit')),0)games_won,coalesce(sum(case when m.team_a_id=t.id then m.team_b_score when m.team_b_id=t.id then m.team_a_score end)filter(where m.status in('completed','forfeit')),0)games_lost from public.teams t left join public.matches m on m.tournament_id=t.tournament_id and t.id in(m.team_a_id,m.team_b_id)group by t.id,m.group_id),scored as(select b.*,games_won-games_lost game_difference,wins*s.points_win+losses*s.points_loss points from base b join public.competition_settings s on s.tournament_id=b.tournament_id)select *,dense_rank()over(partition by tournament_id,group_id order by points desc,wins desc,game_difference desc,games_won desc,team_name)position from scored;

create function public.export_match_results_csv(p_tournament_id uuid)returns text language sql stable security definer set search_path='' as $$select case when private.is_competition_official(p_tournament_id)then 'tournament,stage,round,team_a,team_b,score,winner,status,scheduled_at,completed_at'||E'\n'||coalesce(string_agg(format('%s,%s,%s,%s,%s,%s-%s,%s,%s,%s,%s',replace(t.name,',',' '),replace(s.name,',',' '),m.round_number,replace(a.name,',',' '),replace(b.name,',',' '),coalesce(m.team_a_score,0),coalesce(m.team_b_score,0),replace(coalesce(w.name,''),',',' '),m.status,m.scheduled_at,m.completed_at),E'\n'order by s.sequence_number,m.round_number,m.match_number),'')end from public.matches m join public.tournaments t on t.id=m.tournament_id join public.competition_stages s on s.id=m.stage_id left join public.teams a on a.id=m.team_a_id left join public.teams b on b.id=m.team_b_id left join public.teams w on w.id=m.winner_team_id where m.tournament_id=p_tournament_id$$;
create function public.export_standings_csv(p_tournament_id uuid)returns text language sql stable security definer set search_path='' as $$select case when private.is_competition_official(p_tournament_id)then 'placement,team,played,wins,losses,points,game_difference'||E'\n'||coalesce(string_agg(format('%s,%s,%s,%s,%s,%s,%s',position,replace(team_name,',',' '),played,wins,losses,points,game_difference),E'\n'order by position),'')end from public.public_standings where tournament_id=p_tournament_id$$;
create function public.complete_competition(p_tournament_id uuid)returns uuid language plpgsql security definer set search_path='' as $$declare v_champion uuid;v_runner uuid;begin if not public.is_tournament_role(p_tournament_id,'organizer')then raise exception 'UNAUTHORIZED_REFEREE'using errcode='P0001';end if;if exists(select 1 from public.matches where tournament_id=p_tournament_id and status not in('completed','forfeit','cancelled'))or exists(select 1 from public.match_disputes d join public.matches m on m.id=d.match_id where m.tournament_id=p_tournament_id and d.status='open')then raise exception 'COMPETITION_INCOMPLETE'using errcode='P0001';end if;select winner_team_id,loser_team_id into v_champion,v_runner from public.matches where tournament_id=p_tournament_id and winner_team_id is not null order by round_number desc,completed_at desc limit 1;insert into public.competition_result_snapshots(tournament_id,champion_team_id,runner_up_team_id,settings,standings,matches)select p_tournament_id,v_champion,v_runner,to_jsonb(s),coalesce((select jsonb_agg(to_jsonb(x)order by position)from public.public_standings x where x.tournament_id=p_tournament_id),'[]'),coalesce((select jsonb_agg(to_jsonb(x)order by round_number,match_number)from public.public_matches x where x.tournament_id=p_tournament_id),'[]')from public.competition_settings s where s.tournament_id=p_tournament_id on conflict(tournament_id)do nothing;update public.tournaments set status='completed' where id=p_tournament_id;return p_tournament_id;end$$;

alter table public.competition_settings enable row level security;alter table public.competition_stages enable row level security;alter table public.competition_groups enable row level security;alter table public.competition_group_teams enable row level security;alter table public.matches enable row level security;alter table public.match_games enable row level security;alter table public.match_check_ins enable row level security;alter table public.match_lineups enable row level security;alter table public.match_lineup_players enable row level security;alter table public.match_result_submissions enable row level security;alter table public.match_disputes enable row level security;alter table public.match_schedule_changes enable row level security;alter table public.competition_notifications enable row level security;alter table public.competition_result_snapshots enable row level security;
create policy competition_member_read on public.competition_settings for select to authenticated using(exists(select 1 from public.tournament_members where tournament_id=competition_settings.tournament_id and user_id=(select auth.uid()) and status='active'));create policy stages_member_read on public.competition_stages for select to authenticated using(exists(select 1 from public.tournament_members where tournament_id=competition_stages.tournament_id and user_id=(select auth.uid())and status='active'));create policy groups_member_read on public.competition_groups for select to authenticated using(exists(select 1 from public.tournament_members where tournament_id=competition_groups.tournament_id and user_id=(select auth.uid())and status='active'));create policy matches_member_read on public.matches for select to authenticated using(exists(select 1 from public.tournament_members where tournament_id=matches.tournament_id and user_id=(select auth.uid())and status='active'));
create policy checkins_participant_read on public.match_check_ins for select to authenticated using(private.is_match_captain(match_id)or exists(select 1 from public.matches m where m.id=match_id and private.is_competition_official(m.tournament_id)));create policy lineups_participant_read on public.match_lineups for select to authenticated using(private.is_match_captain(match_id)or exists(select 1 from public.matches m where m.id=match_id and private.is_competition_official(m.tournament_id)));create policy lineup_players_participant_read on public.match_lineup_players for select to authenticated using(exists(select 1 from public.match_lineups l where l.id=lineup_id and(private.is_match_captain(l.match_id)or exists(select 1 from public.matches m where m.id=l.match_id and private.is_competition_official(m.tournament_id)))));create policy submissions_participant_read on public.match_result_submissions for select to authenticated using(private.is_match_captain(match_id)or exists(select 1 from public.matches m where m.id=match_id and private.is_competition_official(m.tournament_id)));create policy disputes_participant_read on public.match_disputes for select to authenticated using(private.is_match_captain(match_id)or exists(select 1 from public.matches m where m.id=match_id and private.is_competition_official(m.tournament_id)));create policy schedule_changes_official_read on public.match_schedule_changes for select to authenticated using(exists(select 1 from public.matches m where m.id=match_id and private.is_competition_official(m.tournament_id)));create policy notification_owner_read on public.competition_notifications for select to authenticated using(recipient_user_id=(select auth.uid())or recipient_user_id is null);create policy result_snapshot_member_read on public.competition_result_snapshots for select to authenticated using(exists(select 1 from public.tournament_members where tournament_id=competition_result_snapshots.tournament_id and user_id=(select auth.uid())));
grant select on public.public_matches,public.public_match_games,public.public_standings to anon,authenticated;grant select on public.competition_settings,public.competition_stages,public.competition_groups,public.competition_group_teams,public.matches,public.match_games,public.match_check_ins,public.match_lineups,public.match_lineup_players,public.match_result_submissions,public.match_disputes,public.match_schedule_changes,public.competition_notifications,public.competition_result_snapshots to authenticated;
revoke all on function private.is_competition_official(uuid),private.is_match_captain(uuid,uuid),private.audit_match(uuid,text,jsonb),private.validate_match_score(public.matches,integer,integer),private.advance_bracket(uuid),private.complete_match(uuid,integer,integer,public.match_status)from public,anon,authenticated;
revoke all on function public.configure_competition(uuid,public.competition_format,integer,integer,integer,integer,integer,jsonb),public.create_competition_group(uuid,text,uuid[]),public.generate_competition_schedule(uuid,timestamptz,integer),public.check_in_team(uuid,uuid,uuid,boolean),public.confirm_match_lineup(uuid,uuid,uuid[],uuid),public.submit_match_result(uuid,integer,integer,text,text,uuid),public.respond_to_match_result(uuid,boolean,text,uuid),public.resolve_match_dispute(uuid,text,integer,integer,text,uuid),public.award_match_forfeit(uuid,uuid,text,uuid),public.reschedule_match(uuid,timestamptz,text),public.export_match_results_csv(uuid),public.export_standings_csv(uuid),public.complete_competition(uuid)from public,anon;
grant execute on function public.configure_competition(uuid,public.competition_format,integer,integer,integer,integer,integer,jsonb),public.create_competition_group(uuid,text,uuid[]),public.generate_competition_schedule(uuid,timestamptz,integer),public.check_in_team(uuid,uuid,uuid,boolean),public.confirm_match_lineup(uuid,uuid,uuid[],uuid),public.submit_match_result(uuid,integer,integer,text,text,uuid),public.respond_to_match_result(uuid,boolean,text,uuid),public.resolve_match_dispute(uuid,text,integer,integer,text,uuid),public.award_match_forfeit(uuid,uuid,text,uuid),public.reschedule_match(uuid,timestamptz,text),public.export_match_results_csv(uuid),public.export_standings_csv(uuid),public.complete_competition(uuid)to authenticated;
alter publication supabase_realtime add table public.matches,public.match_check_ins,public.match_result_submissions,public.match_disputes;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('match-evidence','match-evidence',false,10485760,array['image/png','image/jpeg','image/webp','application/pdf'])on conflict(id)do nothing;
create policy match_evidence_participant_insert on storage.objects for insert to authenticated with check(bucket_id='match-evidence' and exists(select 1 from public.matches m where m.id=((storage.foldername(name))[2])::uuid and(private.is_match_captain(m.id)or private.is_competition_official(m.tournament_id))));create policy match_evidence_participant_read on storage.objects for select to authenticated using(bucket_id='match-evidence' and exists(select 1 from public.matches m where m.id=((storage.foldername(name))[2])::uuid and(private.is_match_captain(m.id)or private.is_competition_official(m.tournament_id))));
alter view public.public_matches set(security_invoker=false);alter view public.public_match_games set(security_invoker=false);alter view public.public_standings set(security_invoker=false);
create function public.set_match_lobby(p_match_id uuid,p_server_id text,p_name text,p_region text,p_password text,p_external_reference text)returns void language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;begin select * into m from public.matches where id=p_match_id;if not private.is_competition_official(m.tournament_id)then raise exception 'UNAUTHORIZED_REFEREE'using errcode='P0001';end if;update public.matches set lobby_server_id=p_server_id,lobby_name=p_name,lobby_region=p_region,lobby_password=p_password,external_match_reference=p_external_reference,revision=revision+1 where id=p_match_id;end$$;
create function public.start_match(p_match_id uuid,p_force boolean default false)returns jsonb language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;v_checks int;v_lineups int;begin select * into m from public.matches where id=p_match_id for update;if not private.is_competition_official(m.tournament_id)then raise exception 'UNAUTHORIZED_REFEREE'using errcode='P0001';end if;select count(*)into v_checks from public.match_check_ins where match_id=p_match_id;select count(*)into v_lineups from public.match_lineups where match_id=p_match_id;if not p_force and(v_checks<>2 or v_lineups<>2)then raise exception 'MATCH_NOT_READY'using errcode='P0001';end if;update public.matches set status='live',started_at=clock_timestamp(),revision=revision+1 where id=p_match_id and status in('scheduled','check_in','ready','rescheduled');if not found then raise exception 'MATCH_NOT_READY'using errcode='P0001';end if;perform private.audit_match(p_match_id,'MATCH_STARTED',jsonb_build_object('forced',p_force));return jsonb_build_object('code','MATCH_STARTED');end$$;
create function public.get_match_operations(p_match_id uuid)returns jsonb language sql stable security definer set search_path='' as $$select case when private.is_match_captain(m.id)or private.is_competition_official(m.tournament_id)then jsonb_build_object('match',to_jsonb(m)-'lobby_password','lobby',jsonb_build_object('server_id',m.lobby_server_id,'name',m.lobby_name,'region',m.lobby_region,'password',m.lobby_password,'external_reference',m.external_match_reference),'check_ins',coalesce((select jsonb_agg(to_jsonb(c))from public.match_check_ins c where c.match_id=m.id),'[]'),'lineups',coalesce((select jsonb_agg(to_jsonb(l))from public.match_lineups l where l.match_id=m.id),'[]'),'submissions',coalesce((select jsonb_agg(to_jsonb(r)-'notes'-'evidence_path')from public.match_result_submissions r where r.match_id=m.id),'[]'),'disputes',case when private.is_competition_official(m.tournament_id)then coalesce((select jsonb_agg(to_jsonb(d))from public.match_disputes d where d.match_id=m.id),'[]')else '[]'::jsonb end)end from public.matches m where m.id=p_match_id$$;
revoke all on function public.set_match_lobby(uuid,text,text,text,text,text),public.start_match(uuid,boolean),public.get_match_operations(uuid)from public,anon;grant execute on function public.set_match_lobby(uuid,text,text,text,text,text),public.start_match(uuid,boolean),public.get_match_operations(uuid)to authenticated;
grant execute on function private.is_competition_official(uuid),private.is_match_captain(uuid,uuid)to authenticated;
revoke select on public.matches from authenticated;
grant select(id,tournament_id,stage_id,group_id,round_number,match_number,team_a_id,team_b_id,scheduled_at,best_of,status,winner_team_id,loser_team_id,team_a_score,team_b_score,check_in_opens_at,check_in_deadline,started_at,completed_at,forfeit_team_id,next_match_id,next_match_slot,revision,created_at,updated_at)on public.matches to authenticated;
create or replace function public.confirm_match_lineup(p_match_id uuid,p_team_id uuid,p_player_ids uuid[],p_request_id uuid default gen_random_uuid()) returns uuid language plpgsql security definer set search_path='' as $$declare m public.matches%rowtype;s public.competition_settings%rowtype;v_lineup uuid;v_player uuid;begin select * into m from public.matches where id=p_match_id for update;if m.status in('completed','forfeit','cancelled') then raise exception 'MATCH_ALREADY_COMPLETED' using errcode='P0001';end if;if not private.is_match_captain(p_match_id,p_team_id) and not private.is_competition_official(m.tournament_id) then raise exception 'NOT_PARTICIPATING_TEAM' using errcode='P0001';end if;select * into s from public.competition_settings where tournament_id=m.tournament_id;if cardinality(p_player_ids)<>s.lineup_size or cardinality(p_player_ids)<>(select count(distinct x)from unnest(p_player_ids)x) then raise exception 'INVALID_LINEUP' using errcode='P0001';end if;if exists(select 1 from unnest(p_player_ids)x where not exists(select 1 from public.tournament_players tp join public.teams tm on tm.id=p_team_id and tm.tournament_id=tp.tournament_id left join public.team_roster tr on tr.player_id=tp.id and tr.team_id=tm.id and tr.is_active where tp.id=x and(tp.user_id=tm.captain_user_id or tr.id is not null)))then raise exception 'INVALID_LINEUP'using errcode='P0001';end if;insert into public.match_lineups(match_id,team_id,confirmed_by)values(p_match_id,p_team_id,(select auth.uid()))returning id into v_lineup;foreach v_player in array p_player_ids loop insert into public.match_lineup_players(lineup_id,player_id,player_ign,is_substitute)select v_lineup,tp.id,tp.ign,coalesce(tr.is_substitute,false)from public.tournament_players tp join public.teams tm on tm.id=p_team_id and tm.tournament_id=tp.tournament_id left join public.team_roster tr on tr.player_id=tp.id and tr.team_id=tm.id and tr.is_active where tp.id=v_player and(tp.user_id=tm.captain_user_id or tr.id is not null);end loop;perform private.audit_match(p_match_id,'LINEUP_CONFIRMED',jsonb_build_object('team_id',p_team_id,'request_id',p_request_id));return v_lineup;end$$;
