"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {PublicDraftPackage} from "@/lib/tournament/public-draft";
import {Card} from "@/components/ui/card";

export function PublicLive({slug,initial}:{slug:string;initial:PublicDraftPackage}){
 const [data,setData]=useState(initial);const [now,setNow]=useState(0);
 useEffect(()=>{const interval=window.setInterval(async()=>{setNow(Date.now());const {data:next}=await createClient().rpc("get_public_draft_package",{p_slug:slug});if(next)setData(next as unknown as PublicDraftPackage)},Math.max(2000,Math.min(10000,data.tournament.spectator_delay_seconds*1000||2000)));return()=>window.clearInterval(interval)},[slug,data.tournament.spectator_delay_seconds]);
 const a=data.auction;const left=a?.closes_at?Math.max(0,Math.ceil((new Date(a.closes_at).getTime()-now)/1000)):null;
 return <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="space-y-6"><Card className="p-6"><div className="flex justify-between gap-4"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Current auction</p><span className="text-sm uppercase text-[var(--accent)]">{a?.status??"waiting"}</span></div><div className="mt-4 flex justify-between gap-4"><div><h2 className="text-3xl font-bold">{a?.ign??"Waiting for nomination"}</h2>{a&&<p className="muted mt-2">{a.primary_role??"Flexible"}{a.secondary_role?` / ${a.secondary_role}`:""} · {a.tournament_mmr} MMR</p>}</div><p aria-label={left===null?"No active countdown":`${left} seconds remaining`} className="text-4xl font-black text-[var(--amber)]">{a?.status==="paused"?"PAUSED":left===null?"—":`${left}s`}</p></div></Card><Card className="p-6"><p className="text-sm text-[var(--muted)]">Current bid</p><p className="mt-2 text-5xl font-black text-[var(--amber)]">{a?.current_bid??a?.opening_bid??"—"}</p><p className="muted mt-2">Leading team: {a?.leading_team??"No bids"}</p></Card><Card className="p-5"><h2 className="font-bold">Draft health</h2><p className="mt-2 font-semibold text-[var(--accent)]">{data.draft_health.code.replaceAll("_"," ")}</p><p className="muted mt-1 text-sm">{data.draft_health.message}</p></Card><div className="grid gap-6 md:grid-cols-2"><Card className="p-5"><h2 className="font-bold">Nomination order</h2><ol className="mt-3 space-y-2">{data.nomination_order.map(n=><li className="flex justify-between border-t border-[var(--line)] pt-2 text-sm" key={n.id}><span>R{n.round_number} · {n.team_name}</span><span>{n.status}</span></li>)}</ol></Card><Card className="p-5"><h2 className="font-bold">Recent accepted bids</h2><ol className="mt-3 space-y-2">{data.recent_bids.map(b=><li className="flex justify-between border-t border-[var(--line)] pt-2 text-sm" key={b.id}><span>{b.team_name}</span><span>{b.amount} CR · <time>{new Date(b.received_at).toLocaleTimeString()}</time></span></li>)}</ol></Card></div></div><div className="space-y-4">{data.teams.map(team=><Card className="p-4" key={team.id}><div className="flex justify-between"><h3 className="font-bold">{team.short_tag} · {team.team_name}</h3><span>{team.credits_remaining} CR</span></div><p className="muted mt-2 text-sm">Captain {team.captain_name} · {team.player_count}/{data.tournament.team_size} players · {team.current_team_mmr} MMR</p><ul className="mt-3 space-y-1 text-sm">{data.rosters.filter(player=>player.team_id===team.id).map(player=><li className="flex justify-between" key={player.player_slug}><span>{player.ign} · {player.primary_role??"Flex"}</span><span>{player.purchase_price??0} CR</span></li>)}</ul></Card>)}</div></div>
}
